### ISSUE TITLE
Relative filters in configuration files are resolved incorrectly

### ISSUE THREAD

**Issue by anb0s** [gcovr/gcovr#567] opened 2022-02-04 15:48 UTC
**Describe the bug**

I'm trying to use `gcovr.cfg` to load dynamic exclude rules, but the relative file parameter is not working as described in the docu:
```
Load that configuration file. Defaults to gcovr.cfg in the --root directory.
```
If i do not add any parameter the file `gcovr.cfg` in root is not loaded, because excludes are not applied.
Therefore i've added the option `--config gcovr.cfg` and face error message, see below.

**To Reproduce**
1. no error, but `gcovr.cfg` is not loaded : `/usr/local/bin/gcovr --html --html-details -r /home/andre/git/project --object-directory=/home/andre/git/project/build/coverage -o test.coverage.html/index.html`

1. add one parameter `--config gcovr.cfg` : `/usr/local/bin/gcovr --html --html-details -r /home/andre/git/project --config gcovr.cfg --object-directory=/home/andre/git/project/build/coverage -o test.coverage.html/index.html`

now the invocation returns error:
```
Traceback (most recent call last):
  File "/usr/local/bin/gcovr", line 8, in <module>
    sys.exit(main())
  File "/home/andre/.local/lib/python3.9/site-packages/gcovr/__main__.py", line 275, in main
    collect_coverage_from_gcov(covdata, options, logger)
  File "/home/andre/.local/lib/python3.9/site-packages/gcovr/__main__.py", line 326, in collect_coverage_from_gcov
    datafiles.update(find_files(search_path, logger, options.exclude_dirs))
  File "/home/andre/.local/lib/python3.9/site-packages/gcovr/gcov.py", line 64, in find_datafiles
    files = list(search_file(
  File "/home/andre/.local/lib/python3.9/site-packages/gcovr/utils.py", line 48, in search_file
    raise IOError("Unknown directory '" + path + "'")
OSError: Unknown directory '--config gcovr.cfg'
ninja: build stopped: subcommand failed.
```

**Expected behavior**
The file `gcovr.cfg` should loaded relative to root as described in the docu.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Debian 11
 - GCC version: GCC 11.1
 - GCOVR version: 5.0
 - Project directory layout:
   - Roots: /home/andre/git/project
   - Object directories: /home/andre/git/project/build/coverage

**Additional context**

**Comment by anb0s** [comment] 2022-02-04 15:53
tried with full path '--config /home/andre/git/plcapp/gcovr.cfg' same error

**Comment by anb0s** [comment] 2022-02-04 16:15
ok, sorry i see that the command produced by CMake script is different:
```
/usr/local/bin/gcovr --html --html-details -r /home/andre/git/project "--config gcovr.cfg" --object-directory=/home/andre/git/project/build/coverage -o test.coverage.html/index.html
```

**Comment by anb0s** [comment] 2022-02-04 16:17
if i execute without quotes and relative path manually
```
/usr/local/bin/gcovr --html --html-details -r /home/andre/git/project --config gcovr.cfg --object-directory=/home/andre/git/project/build/coverage -o test.coverage.html/index.html
```

it shows:
```
Traceback (most recent call last):
  File "/usr/local/bin/gcovr", line 8, in <module>
    sys.exit(main())
  File "/home/andre/.local/lib/python3.9/site-packages/gcovr/__main__.py", line 138, in main
    with io.open(cfg_name, encoding='UTF-8') as cfg_file:
FileNotFoundError: [Errno 2] No such file or directory: 'gcovr.cfg'
```

**Comment by anb0s** [comment] 2022-02-04 16:18
if i use absolute path it executes
```
/usr/local/bin/gcovr --html --html-details -r /home/andre/git/project --config gcovr.cfg --object-directory=/home/andre/git/project/build/coverage -o test.coverage.html/index.html
```

but excludes are not working as expected
```
# use exclude for black-listing
exclude = build/*
exclude = libs/*
```

**Comment by latk** [comment] 2022-02-04 16:25
Indeed, the OsError message suggested that `--config gcovr.cfg` was passed as a single parameter, not as separate command line parameters for name+value.

When you pass an *explicit* `--config`, the path is resolved relative to your current working directory. So `--config gcovr.cfg` is the same as `$(pwd)/config.cfg`. The file path you give will not be adjusted or modified in any way and is just opened directly.

In contrast, the default location if no config path is given is to look into your `--root/-r` directory. Here, that would lead to the path `/home/andre/git/project/gcovr.cfg`.

Filters in config files are resolved relative to the location of the config file. It would be necessary to see more information about your project layout, in particular where exactly your current working directory is and where the config file lies. Looking at `--verbose` output can help to understand what filters were actually loaded.

Config files are still a somewhat experimental feature so it wouldn't be surprising if there are lingering bugs. It is conceivable that you discovered a problem, but it's impossible to tell right now.

**Comment by anb0s** [comment] 2022-02-04 16:52
Thank you for the clarification!

- first issue with explicitly loading the `gcovr.cfg` is not working, because my `$(pwd)` is in object-directory (out-of-source CMake build) here `/home/andre/git/project/build/coverage` and the `gcovr.cfg` is in the source root passed as `-r /home/andre/git/project` --> do not use explicit path to `gcovr.cfg` and it's loaded --> solved

**Comment by anb0s** [comment] 2022-02-04 16:53
- second issue is with understanding how excludes are handled - if it would work relative to location of the config file then this should exclude the two folders:
```
exclude = build/*
exclude = libs/*
```
but it does not.

The exclude is working at command line via absolute paths `-e /home/andre/git/plcapp/build/*` and `-e /home/andre/git/plcapp/libs/*` :
```
/usr/local/bin/gcovr --html --html-details -r /home/andre/git/plcapp -e /home/andre/git/plcapp/build/* -e /home/andre/git/plcapp/libs/* --object-directory=/home/andre/git/plcapp/build/coverage -o test.coverage.html/index.html
```

so how to achive this via `gcovr.cfg` ?

- `exclude = build/*` same like `-e /home/andre/git/plcapp/build/*`
- `exclude = libs/*` same like `-e /home/andre/git/plcapp/libs/*`

i've tried to use variable `${CMAKE_SOURCE_DIR}` set by cmake:
```
exclude = ${CMAKE_SOURCE_DIR}/build/*
exclude = ${CMAKE_SOURCE_DIR}/libs/*
```

but it shows:
```
Traceback (most recent call last):
  File "/usr/local/bin/gcovr", line 8, in <module>
    sys.exit(main())
  File "/home/andre/.local/lib/python3.9/site-packages/gcovr/__main__.py", line 139, in main
    cfg_options = parse_config_into_dict(
  File "/home/andre/.local/lib/python3.9/site-packages/gcovr/configuration.py", line 378, in parse_config_into_dict
    for cfg_entry in config_entry_source:  # type: ConfigEntry
  File "/home/andre/.local/lib/python3.9/site-packages/gcovr/configuration.py", line 1064, in parse_config_file
    raise error("variable substitution syntax "
SyntaxError: /home/andre/git/plcapp/gcovr.cfg: 2: variable substitution syntax (${var}, $(var), or $var) is reserved
on this line: exclude = ${CMAKE_SOURCE_DIR}/build/*
ninja: build stopped: subcommand failed.
```

**Comment by latk** [comment] 2022-02-04 17:39
To clarify, was this verbose mode output generated by adding the exclude flags on the command line (`-e libs/`) or by listing them only in the config file? That the `RelativeFilter(...)` is resolved relative to your working directory suggests that they were listed on the command line, not in the config file. In contrast, if these filters were given in a config file we might have a delightful bug.

As an aside, please note that filters are regexes, not glob patterns. The filters must match a prefix of the path. To exclude all paths that start with the `libs` folder, use `-e libs/` with a trailing slash. In regexes, `/*` would mean “zero or more slashes”. The equivalent in regexes would be `.*` (zero or more arbitrary characters) but since the patterns just have to match at the beginning this is superfluous.

**Comment by anb0s** [comment] 2022-02-04 17:47
> To clarify, was this verbose mode output generated by adding the exclude flags on the command line (`-e libs/`) or by listing them only in the config file? That the `RelativeFilter(...)` is resolved relative to your working directory suggests that they were listed on the command line, not in the config file. In contrast, if these filters were given in a config file we might have a delightful bug.

This was produced by command without `-e` and it loads the excludes from `gcovr.cfg` => it looks like a bug

> As an aside, please note that filters are regexes, not glob patterns. The filters must match a prefix of the path. To exclude all paths that start with the `libs` folder, use `-e libs/` with a trailing slash. In regexes, `/*` would mean “zero or more slashes”. The equivalent in regexes would be `.*` (zero or more arbitrary characters) but since the patterns just have to match at the beginning this is superfluous.

Ok, thanks, i will use right regex here `libs/` and `build/`

**Comment by latk** [comment] 2022-02-04 18:11
Confirmed. Steps to reproduce, in an empty directory:

```bash
#!/bin/bash
echo "pwd=$(pwd)"
echo 'exclude = foo' > gcovr.cfg
mkdir subdir
cd subdir
gcovr -r .. --verbose 2>&1 | grep RelativeFilter
```

Observed output:

```none
pwd=/redacted
- RelativeFilter(foo root=/redacted/subdir)
```

Expected output:

```none
pwd=/redacted
- RelativeFilter(foo root=..)
```

The bug is still present on the master branch.

It can be fixed by applying the following patch in `gcovr/configuration.py`:

```diff
--- a/gcovr/configuration.py
+++ b/gcovr/configuration.py
@@ -420,7 +420,7 @@ def _get_value_from_config_entry(cfg_entry, option):
 
         value = cfg_entry.value
         args = ()
-        if option.type is FilterOption:
+        if issubclass(option.type, FilterOption):
             args = [os.path.dirname(cfg_entry.filename)]
         elif option.type is check_input_file:
             value = check_input_file(value, os.path.dirname(cfg_entry.filename))
```

**Comment by anb0s** [comment] 2022-02-15 12:38
@latk we are using the latest version from pip and my question is if this bug can be fixed in the next release? do you have any timeline?

**Comment by Spacetown** [comment] 2022-02-17 20:04
@anb0s I've created a PR for this. The next [release](https://github.com/gcovr/gcovr/milestone/9) was planned for the end of last months but I'm waiting for review approvals.

**Closed** 2022-02-17 20:56 UTC
Labels: Type: Bug, Filters, cli
