### ISSUE TITLE
gcov output parse error: '%%%%' from gcov flag --all-blocks

### ISSUE THREAD

**Issue by kevinlrak** [gcovr/gcovr#441] opened 2020-12-03 15:47 UTC
One of my gcov files contains this:
```
        -:   67:
        -:   68:#include <iostream>
function sample1::main(int, char**) called 0 returned 0% blocks executed 0%
    #####:   69:int main(int, char**) {
    #####:   70:  std::cout << "Hello." << std::endl;
    %%%%%:   70-block  0
call    0 never executed
call    1 never executed
    #####:   71:  return 0;
        -:   72:}
```

Running gcovr produces the following output:
```bash
$ gcovr --root "`pwd`/build" --filter "`pwd`" --exclude ".*/test/.*" --use-gcov-files --gcov-ignore-parse-errors --keep 
(WARNING) Unrecognized GCOV output for /workspaces/ci-baseline/sample1/src/sample1.cpp
              %%%%%:   70-block  0

        This is indicative of a gcov output parse error.
        Please report this to the gcovr developers
        at <https://github.com/gcovr/gcovr/issues>.
------------------------------------------------------------------------------
                           GCC Code Coverage Report
#[...truncated...]
```

Please let me know if you need any additional information. Thanks!

**Comment by kevinlrak** [comment] 2020-12-03 15:53
Interestingly, invoking gcovr without the `--use-gcov-files` parameter creates a slightly different gcov file which looks like this:
```
        -:   67:
        -:   68:#include <iostream>
function _ZN7sample14mainEiPPc called 0 returned 0% blocks executed 0%
    #####:   69:int main(int, char**) {
    #####:   70:  std::cout << "Hello." << std::endl;
call    0 never executed
call    1 never executed
    #####:   71:  return 0;
        -:   72:}
```

There must be some difference with how gcov is being invoked. I am using this command:
```bash
gcov                     \
  --all-blocks           \
  --branch-probabilities \
  --demangled-names      \
  --relative-only        \
  ${object_file};
```

**Comment by kevinlrak** [comment] 2020-12-03 15:56
I was able to confirm that removing the `--all-blocks` parameter removes the offending line from the gcov output:
```bash
gcov                     \
  --branch-probabilities \
  --demangled-names      \
  --relative-only        \
  ${object_file};
```

produces:
```
        -:   67:
        -:   68:#include <iostream>
function sample1::main(int, char**) called 0 returned 0% blocks executed 0%
    #####:   69:int main(int, char**) {
    #####:   70:  std::cout << "Hello." << std::endl;
call    0 never executed
call    1 never executed
    #####:   71:  return 0;
        -:   72:}

```

**Comment by latk** [comment] 2020-12-03 18:05
Yup, gcovr doesn't currently support block-level coverage. But it could make sense to update the gcov file parser to handle this gracefully.

Background: The raw gcov coverage data (.gcda files) is actually block-level data, where a block is a sequence of assembly instructions without branches. Gcov then works backwards from this to calculate branch coverage and line coverage. Block-level coverage is especially useful when there are sequence operators on one line (e.g. `&&`), when there are multiple statements mushed into one line, or when using C++ lambdas. However, gcovr can't re-associate blocks with the correct parts of the line, so it doesn't bother handling this case.

You've stumbled into the one scenario where this is a problem: the `-g/--use-gcov-files` option. I'd be happy to see a PR that fixes this. Unfortunately, the parsing code isn't very pretty.

**Comment by Spacetown** [comment] 2022-08-06 22:38
Duplicate of #81

**Comment by kevinlrak** [comment] 2022-08-06 23:08
> Duplicate of #81

While I can see how #81 is related, this absolutely isn't a duplicate.

**Comment by Spacetown** [comment] 2022-08-07 07:46
On number next is the correct one.

**Comment by latk** [comment] 2022-08-07 12:41
The new gcov-file parser from gcovr 5.1 correctly parses (and discards) these block coverage lines. I tested the supplied gcov file snippet and gcovr processes it without problem, i.e. as if there were no block-coverage lines.

**Closed by latk** 2022-08-07 12:41 UTC
Labels: Type: Bug, Gcov
