### ISSUE TITLE
TypeError: sequence item 0: expected str instance, list found in formats/gcov/read.py

### ISSUE THREAD

**Issue by jonathanpoelen** [gcovr/gcovr#1043] opened 2024-12-24 11:04 UTC
# Describe the bug

When I launch gcovr, I have the following error:

```py
(INFO) Reading coverage data...
Traceback (most recent call last):
  File "/pyenv/lib/python3.11/site-packages/gcovr/formats/gcov/workers.py", line 81, in worker
    work(*args, **kwargs)
  File "/pyenv/lib/python3.11/site-packages/gcovr/formats/gcov/read.py", line 584, in process_datafile
    errors_output = "\n\t".join(errors)
                    ^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, list found
Traceback (most recent call last):
  File "/pyenv/lib/python3.11/site-packages/gcovr/formats/gcov/workers.py", line 81, in worker
    work(*args, **kwargs)
  File "/pyenv/lib/python3.11/site-packages/gcovr/formats/gcov/read.py", line 584, in process_datafile
    errors_output = "\n\t".join(errors)
                    ^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, list found
(ERROR) Error occurred while reading reports:
Traceback (most recent call last):
  File "/pyenv/lib/python3.11/site-packages/gcovr/__main__.py", line 358, in main
    covdata: CovData = gcovr_formats.read_reports(options)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pyenv/lib/python3.11/site-packages/gcovr/formats/__init__.py", line 85, in read_reports
    covdata = GcovHandler(options).read_report()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pyenv/lib/python3.11/site-packages/gcovr/formats/gcov/__init__.py", line 215, in read_report
    return read_report(self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pyenv/lib/python3.11/site-packages/gcovr/formats/gcov/read.py", line 96, in read_report
    with Workers(
  File "/pyenv/lib/python3.11/site-packages/gcovr/formats/gcov/workers.py", line 177, in __exit__
    self.wait()
  File "/pyenv/lib/python3.11/site-packages/gcovr/formats/gcov/workers.py", line 168, in wait
    raise self.exceptions[0][1]
  File "/pyenv/lib/python3.11/site-packages/gcovr/formats/gcov/read.py", line 103, in read_report
    contexts = pool.wait()
               ^^^^^^^^^^^
  File "/pyenv/lib/python3.11/site-packages/gcovr/formats/gcov/workers.py", line 168, in wait
    raise self.exceptions[0][1]
  File "/pyenv/lib/python3.11/site-packages/gcovr/formats/gcov/workers.py", line 81, in worker
    work(*args, **kwargs)
  File "/pyenv/lib/python3.11/site-packages/gcovr/formats/gcov/read.py", line 584, in process_datafile
    errors_output = "\n\t".join(errors)
                    ^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, list found

sequence item 0: expected str instance, list found
```

# Desktop

- OS: ubuntu
- GCC version 12.2.0
- GCOVR version 8.2

# Additional context

`errors[0]` contains :

```py
# display with line 584 replaced by errors_output = "\n\t".join(map(str, errors))
['Got function _ZZN7CaptureC4ERK13CaptureParamsRK14DrawableParamsbRK9WrmParamsbRK9PngParamsbRK13PatternParamsbRK9OcrParamsbRK20SequencedVideoParamsbRK15FullVideoParamsbRK10MetaParamsbRK12KbdLogParamsRK11VideoParamsP18UpdateProgressDataNS_11CropperInfoE4RectENKUlDpRKT_E2_clIJEEEDaS14_ on multiple lines: 1405, 1416.',
 '\tYou can run gcovr with --merge-mode-functions=MERGE_MODE.',
 '\tThe available values for MERGE_MODE are described in the documentation.'
]
```

**Comment by Spacetown** [comment] 2024-12-24 16:36
This is a duplicate of #996 and fixed on main line.

**Closed** 2024-12-24 16:36 UTC
Labels: Type: Bug
