### ISSUE TITLE
gcovr suggests --merge-mode-functions=MERGE_MODE even though it was invoked with --merge-mode-functions=merge-use-line-min

### ISSUE THREAD

**Issue by tsondergaard** [gcovr/gcovr#862] opened 2023-12-21 12:52 UTC
I have observed gcovr when invoked with --merge-mode-functions=merge-use-line-min or --merge-mode-functions=separate still crashes on AssertionError suggesting to use --merge-mode-functions=MERGE_MODE.

I have fixed the underlying issue in my code base, but still thought that I'd report the issue here as it seems to be a bug. I am not able to provide a repro case, but hopefully the command line and the stacktrace is enough to solve the problem.

```
+ gcovr -j 32 --gcov-ignore-parse-errors --gcov-ignore-errors=no_working_dir_found --merge-mode-functions=merge-use-line-min --xml --root /home/jenkins/workspace/easyviz-pull-requests_PR-2449 '--exclude=.*/tests/.*' '--exclude=build/.*' '--exclude=.*/examples/.*' '--exclude=third-party/.*' '--exclude=mitest/.*' '--exclude=mcop/.*' '--exclude=ftgl/.*' '--exclude-directories=(.+/)?mcopidl$' -o /home/jenkins/workspace/easyviz-pull-requests_PR-2449/build/cobertura-coverage.xml /home/jenkins/workspace/easyviz-pull-requests_PR-2449/build
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "/usr/local/bin/gcovr", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/gcovr/__main__.py", line 328, in main
    covdata = collect_coverage_from_gcov(options)
  File "/usr/local/lib/python3.9/site-packages/gcovr/__main__.py", line 392, in collect_coverage_from_gcov
    covdata = merge_covdata(covdata, context["covdata"])
  File "/usr/local/lib/python3.9/site-packages/gcovr/merging.py", line 190, in merge_covdata
    return _merge_dict(left, right, merge_file, options)
  File "/usr/local/lib/python3.9/site-packages/gcovr/merging.py", line 139, in _merge_dict
    _insert_coverage_item(left, key, right_item, merge_item, options)
  File "/usr/local/lib/python3.9/site-packages/gcovr/merging.py", line 175, in _insert_coverage_item
    merged_item = merge_item(target_dict[key], new_item, options)
  File "/usr/local/lib/python3.9/site-packages/gcovr/merging.py", line 218, in merge_file
    left.functions = _merge_dict(
  File "/usr/local/lib/python3.9/site-packages/gcovr/merging.py", line 139, in _merge_dict
    _insert_coverage_item(left, key, right_item, merge_item, options)
  File "/usr/local/lib/python3.9/site-packages/gcovr/merging.py", line 175, in _insert_coverage_item
    merged_item = merge_item(target_dict[key], new_item, options)
  File "/usr/local/lib/python3.9/site-packages/gcovr/merging.py", line 292, in merge_function
    raise AssertionError(
AssertionError: Got function fhircast::qt_getEnumMetaObject(fhircast::FhircastErrorType) on multiple lines: 19, 20.
	You can run gcovr with --merge-mode-functions=MERGE_MODE.
	The available values for MERGE_MODE are described in the documentation.
```

**Desktop (please complete the following information):**
 - OS: Alma Linux 9 (WSL)
 - GCC version gcc: (GCC) 11.4.1 20230605 (Red Hat 11.4.1-2)
 - GCOVR version: 6.0
 - Project directory layout:
    - CMake based project with out-of-source build directory placed in <src>/build

**Comment by latk** [comment] 2023-12-21 16:24
Thanks for reporting the issue!

I think this might be a duplicate of https://github.com/gcovr/gcovr/issues/841, which should be fixed b https://github.com/gcovr/gcovr/pull/844.

**Closed by latk** 2023-12-21 16:24 UTC
Labels: Type: Bug
