### ISSUE TITLE
gcovr confused by duplicate filenames

### ISSUE THREAD

**Issue by cbagwell** [gcovr/gcovr#60] opened 2014-08-03 22:42 UTC
I saw this issue in a test project where some coverage data was not showing up in the gcovr generated reports.

I believe as of gcovr 3.2, all gcov reports are ran from starting_dir and output is stored in this single directory but nothing in filename contains subdirectory info.

Here is a made up project layout that has plugins for various audio formats:

root/src/main.cpp
root/src/read.cpp
root/src/mp3/read.cpp
root/src/wav/read.cpp

read.cpp.gcov would be generated in root directory 3 times and overwrite each other.

In my tests, only root/src/read.cpp shows up in reports because it happens to be last gcov ran.

**Comment by latk** [comment] 2017-12-28 11:28
This issue has not seen any progress in a while, so I am closing it for now. If the problem persists, please add further details so it can be re-opened. If someone else is experiencing a similar issue, please create a new issue.

In particular, the test case added by @mikael-s in 23b7d41 seems to pass. If that test case does not describe the intended behaviour or if the test case did not reproduce the actual problem, please explain in more detail.
@cbagwell, you seem to understand this issue better than me. Does the problem still exist with an up to date gcovr?

**Closed by latk** 2017-12-28 11:28 UTC
