### ISSUE TITLE
Unexecuted code that lives in root should display as 0% coverage

### ISSUE THREAD

**Issue by aparks5** [gcovr/gcovr#298] opened 2019-03-12 20:31 UTC
i had to run the following to show files that aren't touched at all by my tests, but definitely live in the code base and are used in the primary client program.

i realize that without a *gcda, gcovr has nothing to go on, but its easy enough to find the missing files, why can't they all be marked and displayed as 0% and penalize our code coverage score?

```cd arch-gcov/
ls -1 *gcda > covered.txt
ls -1 *gcno > allgcov.txt
cat covered.txt | cut -d. -f1 > covered.log
cat allgcov.txt | cut -d. -f1 > allfiles.log
diff covered.log allfiles.log 
diff covered.log allfiles.log > no_gtest_coverage.diff
cat no_gtest_coverage.diff ```

**Comment by latk** [comment] 2019-03-12 20:49
Gcovr does process .gnco files when no .gcda files were generated to support exactly your use case.

If that isn't happening, there might be some problem, presumably with filters. The commands you've shown are not really helpful since they just compare file lists, no actual coverage reports. Could you instead

* Tell me your gcovr --version and platform/OS?
* Show the output when running gcovr in --verbose mode?

**Comment by aparks5** [comment] 2019-03-12 21:07
```gcovr --version | head -n1
gcovr 4.1
```
```
$ uname -a
Linux hostname 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
```
gcovr --object-directory="(full path redacted)/i386-gcov/" -r="(full path redacted)" --html-details -o index.html -s --fail-under-line 40 >> coverage_status.json
```
i can't show --verbose output due to the nature of my work, but as an example, here's the output of one of the gcov commands being executed:

```
gcov (file) --branch-counts --branch-probabilities --preserve-paths --object-directory (objdir)
*gcda:cannot open data file, assuming not executed
File 'file.cxx'
No executable lines
No branches
No calls
Removing '(file).gcov'```
```

--keep will keep the gcov files but not include them in the html output

**Comment by latk** [comment] 2019-03-13 11:49
I really cannot reproduce that. Which compiler (gcc or clang) and which version are you using? When I run a test case where there is only a .gcno file and no .gcda file, gcov will produce output like:

``` console
$ gcov /path/to/gcovr/tests/nested/subdir/A/file7.gcno --branch-counts --branch-probabilities --preserve-paths --object-directory /path/to/gcovr/tests/nested/subdir/A
/path/to/gcovr/tests/nested/subdir/A/file7.gcda:cannot open data file, assuming not executed
File 'subdir/A/file7.cpp'
Lines executed:0.00% of 2
No branches
No calls
Creating 'subdir#A#file7.cpp.gcov'
```

And gcovr will happily use the resulting gcov file. I'm not sure why in your case gcov is deleting the file instead. Note that gcovr's --keep option has no effect on the gcov tool.[

I understand that you can't show your code, but without some kind of reproducible example it will be very hard to identify the problem.

**Comment by aparks5** [comment] 2019-03-13 15:32
I'm using GCC5.4
the file in question has executable code

the problem is that the object directory and the source directory differ. even including all the subdirs in the search path does not resolve this issue. 

i see an old issue which was resolved but the fix is a hack to create a file that includes all the headers not executed, which is not really maintainable with a growing codebase https://github.com/gcovr/gcovr/issues/33

i will try to produce a minimal working example and post it

**Comment by latk** [comment] 2019-03-13 23:19
Directory layout issues are very likely not at play here. This seems to be a gcov thing.

I have just created & observed a test case with an uncovered file that works fine on GCC 5.5.0 / Ubuntu but fails to show the uncovered file under GCC 5.3.0 / MinGW-W64 (Windows). In that sense, I managed to confirm both that gcovr works correctly and that the bug exists.

I am not sure what can be done here.

* It might be possible to extract the source file name from gcov stdout output and display empty coverage data in the reports. However, this would skew coverage metrics, and more importantly: this would be indistinguishable from files that genuinly have no coverage. I don't think I will do that.

* I can add a paragraph about these issues to the documentation (I'm leaving this issue open as a reminder).

Besides that, this seems to be an upstream bug in some versions of gcov. Users can avoid this by **upgrading GCC**. I think this bug was fixed in GCC Revision 239413 on 2016-08-12 (gcc-mirror/gcc@6d5f72f3176e6a0da33bb3495f0f4797cc2ad9db). I would expect all later [releases](https://gcc.gnu.org/releases.html) (5.5+, 6.2+, 7+) to include the fix.

**Comment by aparks5** [comment] 2019-03-13 23:41
thank you for your thorough investigation!

to provide some context, the bigger picture here is that, for a large legacy code base with few existing tests, having uncovered files displayed in HTML demonstrates to stakeholders the extent to which code is largely untested. 

this hopefully puts some hard numbers on the extent to which code is untested, and also provides a sense of progress as classes are put under test.

as a back of the envelope calculation i used `find . -name "*.cxx" | wc -l | head -n 1` to estimate the total lines of code (i realize with comments and whitespace this probably overestimates), and estimated coverage based on ```true coverage = gcov estimate / LOC from bash```.

**Closed** 2019-03-14 13:37 UTC

**Comment by latk** [comment] 2019-03-14 13:45
Ok, I wrote an FAQ entry about this problem (will be deployed to the website with the next release).

You might be interested in the [`sloccount` tool](https://dwheeler.com/sloccount/) (available in the Ubuntu repositories) for a more accurate line count. That will still underestimate your coverage (declarations vs executable statements, lines vs statements), but it would be far more accurate than `wc -l`.

**Comment by aparks5** [comment] 2019-03-14 15:28
As a note for people, I would really advice against upgrading your local machine's gcc version if your team uses a complex and fragile toolchain. I spent hours undoing the damage I unleashed by upgrading gcc to try to accomplish this. Next time I try something like that I'm going to use a VM.

**Comment by latk** [comment] 2019-03-14 15:59
I'm sorry that you encountered these difficulties. It is possible to
install multiple GCC versions side by side.
If you want to compile GCC yourself, use a suitable prefix (do not
override your existing installation, and instead manipulate your PATH
to select the correct version). See the installation guide
(https://gcc.gnu.org/install/configure.html).

Many Linux distros package multiple GCC versions. E.g. Ubuntu 18.04
has gcc-5, gcc-8, and so on in the main repositories and many
additional versions if we add the Ubuntu Toolchain PPA
(https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test). I
can also recommend putting more fiddly toolchains into a Docker
container.

**Comment by ssureshbabu27** [comment] 2021-12-16 09:30
Hi @aparks5 , thanks for bringing this issue. Even i am facing the same issue, where the coverage report does not report the file where UT is not available. This results in high coverage value in few places. Please let me know if you got any solution.

In the meanwhile i can Sonarqube has some feature to include all the files, below is for reference:
https://blog.sonarsource.com/executable_lines

Please let me know if you have found any solution to include all the files which does not have UT as well.
