### ISSUE TITLE
Unrecognized GCOV output

### ISSUE THREAD

**Issue by fuchsth** [gcovr/gcovr#715] opened 2023-02-15 08:46 UTC
**Describe the bug**
When running gcovr on coverage output generated by Cygwin gcc 11.3 for some files a parse error is issued. It shows the following error message:

(WARNING) Unrecognized GCOV output for /cygdrive/d/N/workspace/e9ad3d430af280a6/23b21979/build/gcc_x86-64_VRR1_default/M_brosdk/test/CMakeFiles/m_brosdk_tests.dir/core/gui/osd/source/gtest-internal.h
	  branch  5 taken -2 (fallthrough)
	This is indicative of a gcov output parse error.
	Please report this to the gcovr developers
	at <https://github.com/gcovr/gcovr/issues>.
(WARNING) Exception during parsing:
	UnknownLineType: branch  5 taken -2 (fallthrough)
(ERROR) Exiting because of parse errors.
	You can run gcovr with --gcov-ignore-parse-errors
	to continue anyway.
(ERROR) Trouble processing '/cygdrive/d/N/workspace/e9ad3d430af280a6/23b21979/build/gcc_x86-64_VRR1_default/M_brosdk/test/CMakeFiles/m_brosdk_tests.dir/core/gui/osd/source/test_osd_event_touch.cpp.gcda' with working directory '/cygdrive/d/N/workspace/e9ad3d430af280a6/23b21979'.
Stdout of gcov was >>File 'D:/N/workspace/e9ad3d430af280a6/23b21979/M_brosdk/test/core/gui/osd/source/test_osd_event_touch.cpp'
Lines executed:100.00% of 12
No branches
No calls
Creating 'test_osd_event_touch.cpp##0ae0cac0651cf67ab453304d94195317.gcov'

**To Reproduce**
1. Setup test with google test frame work and Cygwin gcc
2. Run test
3. Execute gcovr
4. Issue seems to be persisent with the gtest-internal.h also for other files

**Expected behavior**
Error shall be not issued

**Screenshots**
See build log excerpt

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GCC version: Cygwin gcc (GCC) 11.3.0
 - GCOVR version: 5.2
 - Project directory layout:
 - root
        build / gcc_x86-64_VRR1_default / M_brosdk / test / CMakeFiles / m_brosdk_tests.dir / core / gui / osd / source / test_osd_event_touch.cpp.gcda
        build / gcc_x86-64_VRR1_default / M_brosdk / test / CMakeFiles / m_brosdk_tests.dir / core / gui / osd / source / test_osd_event_touch.cpp.gcno
         test_osd_event_touch.cpp#0ae0cac0651cf67ab453304d94195317.gcov
   - Object directories

**Additional context**

[test_osd_event_touch.zip](https://github.com/gcovr/gcovr/files/10741078/test_osd_event_touch.zip)

**Comment by Spacetown** [comment] 2023-02-15 08:55
Duplicate of #583. This is a `gcov` bug and not related to `gcovr`.

**Closed by Spacetown** 2023-02-15 08:55 UTC
Labels: Type: Bug
