### ISSUE TITLE
add "--add-tracefile" like lcov

### ISSUE THREAD

**Issue by whart222** [gcovr/gcovr#10] opened 2013-09-02 17:45 UTC
I want to merge two gcda result into one.
lcov can use --add-tracefile do the work, how gcovr do it? Thanks

**Comment by wichtounet** [comment] 2015-06-14 18:42
Such a feature would indeed be great. I also have the need for it with several object directories.

**Comment by verbitan** [comment] 2016-11-23 17:25
This is exactly the feature I'd like as well, so a vote for this issue from me :+1:

**Comment by pbregener** [comment] 2016-12-12 15:11
I'm interested in this feature as well 👍

**Comment by pbregener** [comment] 2016-12-14 12:50
@whart222 As you opened this issue 3 years ago and now seem to be the maintainer of gcovr - any thoughts on this?

**Comment by pbregener** [comment] 2017-01-13 13:51
ping @whart222

**Comment by latk** [comment] 2018-10-12 21:57
While working on a new internal data model (191b30cd3d7a0377341dcfc42b8ea24681614dce) I realized that merging coverage data is not actually difficult – such merging is already done internally to combine the coverage from multiple object files. All that is missing is to serialize and deserialize that data. In particular:

 - a new generator that dumps the complete coverage data into a file, preferably as JSON.
 - an option to load such a files so that additional coverage can be merged. “Steal” the design of that option from lcov?

This file format should allow some sanity checks, for example that all runs must use the same options.

The file format could be modeled after the upcoming gcov json format (see #282) which would allow for some interesting synergies, but this is not necessary.

If anyone would like to take on this work, please do :) As per the [contribution guidelines](https://github.com/gcovr/gcovr/blob/master/CONTRIBUTING.rst#how-to-submit-a-pull-request): if you need help please ask in the [Gitter chat](https://gitter.im/gcovr/gcovr), discuss the design on this issue, or open a WIP pull request.

**Comment by CezaryGapinski** [comment] 2019-08-16 15:54
Hi!

I am trying to make add-tracefile option with JSON files. I have noticed that something can be wrong with `LineCoverage` class [constructor](https://github.com/gcovr/gcovr/blob/1f5af01d1a347c917939df34082254544d85a5f1/gcovr/coverage.py#L68) and [update method](https://github.com/gcovr/gcovr/blob/1f5af01d1a347c917939df34082254544d85a5f1/gcovr/coverage.py#L106).
Maybe I missed something, but `noncode` fileld should be set to True as a default value?
During update when one of the object has `noncode` field cleared and the other has it set that means the line is still real code, filed shouldn't be set and line should be taken into coverage?

**Comment by latk** [comment] 2019-08-16 16:17
@CezaryGapinski Thank you for looking into this! That's a really good question, and I'm not entirely sure what the proper behaviour should be. Each line can have three states: covered, uncovered, noncode. A line that has no coverage data is implicitly noncode.

Noncode is not the default because when we create LineCoverage, that's usually because there is code on the line. If you find this problematic, it would be better to make that argument non-optional.

When I created this data model I just followed the previous design, which used set operations for convenience. Maybe it would be better to combine the flag with `&` rather than `|`, so that the covered/uncovered states dominate over the noncode state. I don't think a conflict could even occur during normal usage, so this shouldn't matter.

Please do what you think is best :) If your changes would break something, the test suite should complain.

**Comment by CezaryGapinski** [comment] 2019-08-17 07:24
@latk 

>If your changes would break something, the test suite should complain.

It complains a lot, because change in `LineCoverage` changing `GcovParse`r behaviour :).

I have pushed branch to my fork [repository](https://github.com/CezaryGapinski/gcovr/commits/json_add_coverages) to show you an example, where is the problem. You can take a look on my test named "add_coverages" where I have two functions called depended on macro definition set by the compiler command line.

Without changing the `noncode` filed in `LineCoverage` class, generating report with merged two coverage results are wrong and shows that `foo()` and `bar()` functions were not called. With change in `LineCoverage` merged results are fine, but it has a bad impact on `GcovParser` :(.

Maybe I did something stupid in my code, but I stuck with that, so I would be grateful for any suggestions.

BTW: lcov with this example works fine.

**Comment by latk** [comment] 2019-08-17 09:13
@CezaryGapinski  Ok the problem is this: when a `.line()` of a FileCoverage object is accessed, a new LineCoverage object is instantiated if that line doesn't already exist.

(1) In the GcovParser, new lines usually contain coverage data. Making them `noncode` is wrong.

(2) When merging/updating coverage data, new lines should not affect the coverage. They have to be a “neutral element” regarding update(). I.e. we need to ensure:

``` python
new = LineCoverage(old.lineno)
new.update(old)
assert new == old  # doesn't actually have an equals operator
```

All of this previously worked fine because `False` is the neutral element for the `|` operator. You've changed the default to `True` which is the neutral element for `&`, but this violates requirement (1) leading to test case failures.

The simplest alternative I see is to stick to the old default, but to let the `FileCoverage.line()` function take defaults so that the `update()` method can get a neutral element:

``` diff
- def line(self, lineno):
+ def line(self, lineno, **defaults):
     try:
         return self.lines[lineno]
     except KeyError:
-        self.lines[lineno] = line_cov = LineCoverage(lineno)
+        self.lines[lineno] = line_cov = LineCoverage(lineno, **defaults)
         return line_cov

 def update(self, other):
     for lineno, line_cov in other.lines.items():
-        self.line(lineno).update(line_cov)
+        self.line(lineno, noncode=True).update(line_cov)
```

With this change, all tests incl. your JSON tests pass :)

**Comment by CezaryGapinski** [comment] 2019-08-17 11:16
@latk Thanks! You are my hero of the day :).
Updated version is on my forked repo.
Do you think that is good enough to make a pull request to add this new feature to gcovr?

**Comment by latk** [comment] 2019-08-17 11:28
Awesome! Yes, please do open a PR. Per my skimming this looks really good, but there are some details about the JSON usage that I'd like to discuss.

I'm really excited about this --add-tracefile feature because this makes it possible to simplify the test suite a lot (separating gcov-level tests from report generator tests)

**Closed** 2019-11-02 17:27 UTC
Labels: Type: Enhancement, help wanted
