### ISSUE TITLE
Unrecognized GCOV output in Debian Trixie

### ISSUE THREAD

**Issue by kop316** [gcovr/gcovr#884] opened 2024-02-14 02:56 UTC
**Describe the bug**
Hello! I am getting an error in my CI with gcovr, and it says to report it here: 

https://gitlab.gnome.org/World/Chatty/-/jobs/3568664#L3441

This is on Debian Trixie. 

The error is:
```
(WARNING) Unrecognized GCOV output for /builds/World/Chatty/_build/src/chatty-resources.c
	      %%%%%:13494-block  0
	      %%%%%:13677-block  0
	      %%%%%:13682-block  0
	This is indicative of a gcov output parse error.
	Please report this to the gcovr developers
	at <https://github.com/gcovr/gcovr/issues>.
(WARNING) Exception during parsing:
	UnknownLineType:     %%%%%:13494-block  0
(WARNING) Exception during parsing:
	UnknownLineType:     %%%%%:13677-block  0
(WARNING) Exception during parsing:
	UnknownLineType:     %%%%%:13682-block  0
(ERROR) Exiting because of parse errors.
	You can run gcovr with --gcov-ignore-parse-errors
	to continue anyway.
(ERROR) Trouble processing '/builds/World/Chatty/_build/src/libchatty.a.p/meson-generated_.._chatty-resources.c.gcno' with working directory '/builds/World/Chatty/_build'.
Stdout of gcov was >>File 'src/chatty-resources.c'
```

**To Reproduce**
Enable coverage on my CI, and run `ninja -C _build coverage`

**Comment by Spacetown** [comment] 2024-02-14 18:47
This is a duplicate of #882 and solved on main branch with #883.

**Closed by Spacetown** 2024-02-14 18:47 UTC
Labels: Type: Bug
