### ISSUE TITLE
Reported coverage changes with 3.2 -> 3.3

### ISSUE THREAD

**Issue by betatim** [gcovr/gcovr#140] opened 2016-08-18 14:37 UTC
Hi,

we are using `gcovr` for `dib-lab/khmer` and recent PRs have been reporting a much lower coverage than previously (even if they change non-code stuff). After some searching we tracked it down to a difference between `gcovr 3.2` and `v3.3` (python2).

An example of what happens is: https://codecov.io/gh/dib-lab/khmer/pull/1418/commits or https://github.com/dib-lab/khmer/pull/1418/commits

The only difference between the top two commits is the `gcovr` version. It seems the change is mostly from "hit" to "partial". Wanted to get your opinion on whether this is because `gcovr` got better at spotting this or might this be a bug in `gcovr`?

If there is some test I can do or extra info let me know.

**Comment by whart222** [comment] 2016-08-18 14:47
Can you point me to coverage reports that reflect this?  I'm not sure I saw
changes in coverage for the gcovr tests.  I'd like to see if we can come up
with a simple example to test this.

**Comment by betatim** [comment] 2016-08-18 15:07
You mean the individual XML files that are fed into codecov? Not sure I can find the originals but I uploaded two that I just created locally here: https://gist.github.com/betatim/36cc341ce672c53476f09f3e1d0176cf

**Comment by whart222** [comment] 2016-08-21 14:50
Do you have any idea what aspects of the code reflect these differences?  I'm not sure how to replicate this issue.

**Comment by whart222** [comment] 2016-08-21 16:44
After staring at the code for a few hours, I have a hypothesis of what changed.  In commit 0cb3bfe the definition of 'non-code' lines was extended to ignore lines with just '(', ')' or ';' characters.

Can you confirm that this is indicative of the changes in that you see?

**Comment by whart222** [comment] 2016-08-21 17:19
I've added a new test, simple1, to verify my hypothesis.  Commit d701d30 reverts the change in 0cb3bfe related to non-code semantics.  Is there a way for you to verify this fix?

**Comment by betatim** [comment] 2016-08-26 07:28
Thanks a lot for looking into this. I've been away and catching up with things, I will try this out and get back to you.

**Comment by whart222** [comment] 2016-08-26 13:39
OK.  I'm waiting to see if this works for you before cutting a new release.

**Comment by betatim** [comment] 2016-08-29 14:16
I updated the [gist with the coverage files](https://gist.github.com/betatim/36cc341ce672c53476f09f3e1d0176cf) to include one produced with `gcovr-master` from just now.

Here is a [gist with the tabular output](https://gist.github.com/betatim/8114cbb6ecc2b27eebf4a62132f1f19c) for 3.2 vs master.

Wondering if I am doing something wrong?

**Comment by betatim** [comment] 2016-08-29 15:24
After some more poking around: if I remove the `--exclude-unreachable-branches` flag from my v3.2 command line I get a table that looks very similar to the one in v3.3. So I suspect that `--exclude-unreachable-branches` was not doing what we thought it was doing in v3.2? A completely empty table as output seems wrong.

(I'm new to the codebase where this is happening (and `gcovr`) so not much insight about "the past" and how things used to look.)

**Comment by whart222** [comment] 2016-08-29 16:04
Hmmm. Let me look into that.  I'm not sure how the semantics of unreachable
branches changed

**Comment by betatim** [comment] 2016-08-30 12:12
To make things even more complex, I found a link to `git+https://github.com/nschum/gcovr.git@never-executed-branches` that was used at one point instead of `gcovr` from PyPI.

**Comment by latk** [comment] 2018-01-08 16:48
This issue has not seen any progress in a while, so I am closing it for now. If the problem persists, please add further details so it can be re-opened. If someone else is experiencing a similar issue, please create a new issue.

The problem may very well still exist. But without a short (!) example to reproduce the problem, it is impossible to debug this and locate the reason for the regression. The current gcovr output _seems_ correct, though of course rapidly changing fluctuation is troubling.

**Closed by latk** 2018-01-08 16:48 UTC
