### ISSUE TITLE
Headers containing definitions are filtered in out-of-source build

### ISSUE THREAD

**Issue by mjvankampen** [gcovr/gcovr#329] opened 2019-08-28 08:43 UTC
It seems that headers that contain definitions (such as templates) that are included in other cpp files get a path in gcov that is lower-case on windows (not sure on other OS). This means they do not match the root path anymore. Could the root filter be case-insensitive or do you feel this is an issue with gcov/gcc (6.3.0) and it should be fixed there? For me this seems like the directory is matching so this should not be filtered.

```
Finding source file corresponding to a gcov data file
  currdir      C:\Soft_Dev\590008\JLSCONTROL\JLSOCSOURCE\build
  gcov_fname   C:\Users\mjvk\AppData\Local\Temp\tmp00sj52vb\c~#soft_dev#590008#jlscontrol#jlsocsource#master#mastercommon#include#mastercommon#votercoremessages.hpp.gcov
               ['        -', '    0', 'Source', 'c:/soft_dev/590008/jlscontrol/jlsocsource/master/mastercommon/include/mastercommon/votercoremessages.hpp\n']
  source_fname C:\Soft_Dev\590008\JLSCONTROL\JLSOCSOURCE\build\core\src\CMakeFiles\libocscore.dir\CoreScheduler.cpp.gcda
  root         C:\Soft_Dev\590008\JLSCONTROL\JLSOCSOURCE\MASTER
  fname        c:\soft_dev\590008\jlscontrol\jlsocsource\master\mastercommon\include\mastercommon\votercoremessages.hpp
Parsing coverage data for file c:\soft_dev\590008\jlscontrol\jlsocsource\master\mastercommon\include\mastercommon\votercoremessages.hpp
  Filtering coverage data for file c:\soft_dev\590008\jlscontrol\jlsocsource\master\mastercommon\include\mastercommon\votercoremessages.hpp
```

**Comment by latk** [comment] 2019-09-09 15:36
Thank you for raising this issue. I think you're right that gcovr should switch to case-insensitive matching in this case.

I have not previously done that because I'm not sure which precise paths should be case-insensitive on which operating system. If I remember correctly, case insensitivity is not a feature of Windows but an optional feature of the NTFS filesystem, but it would be impractical to try to detect that. I'm also not sure how that would interact with environments like MSYS.

Do you have more insight regarding when case-folding should be applied? Should this be user-configurable? Or should gcovr just ignore case under all circumstances on Windows? From the output you show it seems like gcc just lowercases all filenames, which could be done as well.

If you need to patch this yourself, you can make all filters case-insensitive by making the following change in `gcovr/utils.py`:

``` diff
 class Filter(object):
     def __init__(self, pattern):
-        self.pattern = re.compile(pattern)
+        self.pattern = re.compile(pattern, re.IGNORECASE)
```

**Comment by mjvk** [comment] 2019-10-11 08:57
Sorry it's taking a while to get back to this, will try to get back asap!

**Comment by Spacetown** [comment] 2020-05-27 21:06
It doesn't depend on the file system. Windows is always case insensitive. You can crate files with different case through the API but can open only one file.
I use MSYS at work and this is also case insensitive.

**Comment by mjvk** [comment] 2020-05-28 10:28
Thanks @Spacetown for bringing this up again, I forgot! I agree with you that gcovr should ignore case when Windows.

**Comment by latk** [comment] 2020-05-28 10:46
Ok, so the solution would be:

* by default, ignore case of file paths on Windows
* add a CLI option to override the ignore case mode

What would be a suitable name for that option? `--flters-ignore-case`/`--no-filters-ignore-case`?

**Comment by Spacetown** [comment] 2020-05-28 20:19
On POSIX systems the option doesn't make sense for me. On Windows I don't see a need to compare case sensitive.
I think the compare shall be case sensitive if the file system is case sensitive. I've found several solutions all pointing to [check a temporary file](https://stackoverflow.com/questions/7870041/check-if-file-system-is-case-insensitive-in-python). The solution from Nov. 19 sounds good for me:
```python
import os.path
home = os.path.expanduser('~')
is_fs_case_insensitive = os.path.exists(home.upper()) and os.path.exists(home.lower())
```

**Comment by latk** [comment] 2020-05-28 20:31
That's a reasonable argument against adding an option, and a clever way to check for case sensitivity. Though I think there might be less breakage/edge cases if we check an actual file in the project being covered (1). The --root path looks like a reasonable candidate unless it's set to `/` on Unix, but I don't think anyone would seriously do that.

(1) My concern is that a Linux user would have a case sensitive file system for home, but have mounted a case-insensitive NTFS for their code, just to torture gcovr. But that's admittedly a very niche use case, compared to people actually using Windows. I tend to overvalue correctness, so I would merge a fix that doesn't address this concern :sweat_smile:

**Comment by Spacetown** [comment] 2020-05-28 20:35
What about using the python executable? This is always a valid path.

**Comment by latk** [comment] 2020-05-28 20:44
I'm happy with _any_ path, although I strongly suspect there might be edge cases as discussed above. But I expect those edge cases to be so rare that I would ignore them for now. Using something like python or home is nice and simple.

If and when someone reports a bug because their project is on a different filesystem, then we can figure out a more correct solution. I'm still scared/amazed by #284 where there was an extremely niche file path handling problem that I would have never dreamed of.

**Comment by Spacetown** [comment] 2020-05-28 21:17
@mjvk: Can you check thiis commit on Windows?

**Comment by giantmustache** [comment] 2020-06-11 12:32
I was able to test the branch and found that this commit does work for us on Windows. The files are now included in our coverage report.

**Comment by Spacetown** [comment] 2020-06-11 12:35
Thanks. PR is waiting for review.

**Comment by chrober** [comment] 2021-09-17 07:27
Is there a regression in gcvor 5.0 regarding this fix?

I have just started to use gcovr 5.0 (never used an older version) and see a very similar problem to what @mjvankampen described originally.

I am using GCC 6.5.0 and gcovr 5.0 on Windows 10.
I can see pathfilenames from inlined header-files have been converted to lower-case by gcc (e.g. calling gcov-dump on the generated gcno-files already reveals lowercased filenames).

This seems to confuse gcovr when processing the gcda/gcno files: The problem is I get some of the header-files listed twice in the html-report, obviously gcovr recognizes them as different files (because of treating filenames case-sensitive?).

**Comment by Spacetown** [comment] 2021-09-17 07:29
Do you include the header in different files with different cases?

**Comment by chrober** [comment] 2021-09-17 07:33
No, I don't.

GCC converts the full path to lowercase. Even those parts of the path that never show up in an `#include` statement but only in the `-I` command line option.

**Comment by chrober** [comment] 2021-09-17 08:20
Here is an example:
TaskQueue.h is one my header files for which I get two entries in the HTML report.
For the build I am currently inspecting this file was located at `E:\Jenkins\ws\GcovBuild\proj\MyLib\Treatment\TaskQueue.h`.

On the gcovr overview page it is listed as 
`MyLib/Treatment/TaskQueue.h`
and
`proj/MyLib/Treatment/TaskQueue.h`

On the corresponding detail pages for those two file entries the filenames are reported as
`MyLib\Treatment\TaskQueue.h`
and
`e:\jenkins\ws\gcovbuild\proj\mylib\treatment\taskqueue.h`

**Comment by Spacetown** [comment] 2021-09-17 10:35
Is the working directory changed for the compilation of the files?

**Comment by chrober** [comment] 2021-09-17 10:48
> Is the working directory changed for the compilation of the files?

No, nothing was moved or changed. I should mention that I run a cross-compilation project, i.e. the actual run for collecting coverage data is not on the Windows machine but on an embedded platform. However, after the run the gcda-files are copied back to the build workspace with the proper directory hierarchy, so every gcda-files is right next to its corresponding gcno-file.

And: I have good news on the issue! A colleague of mine who is more familiar with python than I am supplied me with a small change for `gcov.py` which seems to have solved this problem. I'll do some more testing of this patched gcovr (only on Windows, unfortunately) and if everything seems OK, we'll hand over this patch to you for further review.

**Comment by Spacetown** [comment] 2021-09-17 18:31
> On the gcovr overview page it is listed as
> `MyLib/Treatment/TaskQueue.h`
> and
> `proj/MyLib/Treatment/TaskQueue.h`

But here the problem isn't the case. I'm looking forward for the patch.

**Comment by gmc-devel** [comment] 2021-09-20 11:10
We (I.e, with @chrober) have seen, that GCC (as cross-compiler, running on WIndows) will (sometimes) store the filename of header-files containing the definition of  inlined (!) code in lowercase at compile-time in the generated .gcno-file. In this case the gcov-tool will also work with a lower-case (variant) of this file and also gcovr afterwards ...
> File 'e:/source/inc/managerimpl.h'
> Creating 'managerimpl.h.gcov'

Or work-around is specific for windows (case-insensitive, but case-preserving OS) and is based on https://stackoverflow.com/questions/3692261/in-python-how-can-i-get-the-correctly-cased-path-for-a-file ...

I.e., within guess_source_file_name() casing will be "fixed" for an already existing file by following change (unified diff):
```
--- gcovr/gcov.py.bak	Tue Sep  7 08:12:05 2021
+++ gcovr/gcov.py	Mon Sep 20 12:50:57 2021
@@ -22,6 +22,7 @@
 import subprocess
 import sys
 import io
+from pathlib import Path
 
 from .utils import search_file, Logger, commonpath
 from .workers import locked_directory
@@ -157,6 +158,7 @@
         fname = guess_source_file_name_heuristics(
             gcovname, currdir, root_dir, starting_dir, obj_dir, source_fname)
 
+    fname = str(Path(fname).resolve())
     logger.verbose_msg(
         "Finding source file corresponding to a gcov data file\n"
         '  currdir      {currdir}\n'
```
This simple change has fixed our issue of "wrong" generated/assumed filenames with lowercase. As said before, this work-around is specific for windows and I don't know how to express a much more generic solution which is also valid for linux; I.e., I'm not really familiar with python .. Sorry!

**Comment by latk** [comment] 2021-09-20 13:33
Thanks @gmc-devel! That kind of patch looks pretty reasonable, I'll try to see how that can be integrated.

**Comment by LukiBa** [comment] 2022-11-23 15:23
@latk what happened to the suggested fix of @gmc-devel? Is it planned to be integrated?

**Comment by latk** [comment] 2022-11-23 19:17
@LukiBa I have found very little energy this year to work on gcovr. I'm not sure what the status of this fix is. If it isn't already included, you (or any one else) are more than welcome to write a pull request (change, simple test case, changelog entry) and to get it merged by one of the other dozen people with write access.

**Comment by Spacetown** [comment] 2022-11-24 05:48
With #329 only the filter was switched to case insensitive. This problem is a different case for the same file where the file is listed twice.
I'll try to find some time to check this.

**Comment by LukiBa** [comment] 2022-11-24 07:13
@Spacetown If that's ok with you, I'll create a pull request that fixes this problem.
There are two options to solve that issue:
1. The minimal fix suggested by @gmc-devel 
2. Switch all path operations from os to pathlib. This would have the advantage that pathlib abstracts the differences caused by the operating system. This could prevent such problems in the future.

**Comment by Spacetown** [comment] 2022-11-26 07:58
@LukiBa Please do it

**Closed** 2023-02-15 21:25 UTC
Labels: Type: Bug, help wanted, good first issue, Platform: Windows, Filters
