### ISSUE TITLE
HTML index by folder

### ISSUE THREAD

**Issue by inigo-selwood** [gcovr/gcovr#544] opened 2021-12-27 15:17 UTC
# HTML report folder navigation

`lcov` lets me navigate the coverage report like a file system, showing coverage for both files and folders.

I'd like to see the detailed html report organized by file _and_ by folder

---

For instance, with a file system like this

```
source/
├── some_folder
│   ├── file_one.cpp
│   └── file_two.cpp
└── some_other_folder
    └──   file_three.cpp
```

Currently, with the command:

```
gcovr --root source/ --html-details coverage.html
```

You get a report which looks like this

![current](https://user-images.githubusercontent.com/7069966/147484440-83301ffd-caf8-4b95-a350-769078a797dd.PNG)

---

I'm proposing this be broken down into its subfolders, `some_folder` and `some_other_folder`. This way, the index would show:

![proposed-folder](https://user-images.githubusercontent.com/7069966/147484816-1a6c4e37-6ff8-4fdf-b9c2-00bb9a176184.PNG)

And clicking on `some_folder` would show the index for that folder:

![proposed-file](https://user-images.githubusercontent.com/7069966/147484521-3a24f789-3445-4ea8-ab07-1d8416f4b2e8.PNG)

Thoughts?

**Comment by Spacetown** [comment] 2021-12-27 16:08
As mentioned in #160 this is a often requested feature. There is one PR for the HTML open, after this we can try to add this.

**Comment by inigo-selwood** [comment] 2021-12-27 18:47
If I created a PR for this issue, would you be able to review it? How large is the ongoing HTML PR?

**Comment by Spacetown** [comment] 2021-12-27 20:15
I'm still waiting for a reviewer.

**Comment by Spacetown** [comment] 2022-01-07 19:34
Review is done.

**Comment by Spacetown** [comment] 2022-01-11 21:05
@inigo-selwood Are you working on this? If not I'll do that.

**Comment by inigo-selwood** [comment] 2022-01-16 13:30
@Spacetown I'm giving it a go. I'll let you know if I get anywhere :D

**Comment by keith-bennett-airmap** [comment] 2022-06-09 23:56
Hi guys, I'm happy to see that gcovr is being actively maintained. I also would like HTML output as described in the top of this issue. I understand this issue may be a duplicate of #160 -- but I think this description (with its screenshots) better captures what an end goal might look like.

I also see that there hasn't been activity on either of these issues for about six months. Is (or was) someone actively working towards it?

**Comment by Spacetown** [comment] 2022-06-10 06:33
@inigo-selwood have you started on this?

**Closed** 2023-01-07 16:34 UTC
Labels: Type: Enhancement, Format: HTML
