### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/data00/home/<stdin>##5877c01ccd0be143f73271645c2caa3d.gcov'

### ISSUE THREAD

**Issue by nolongerwait** [gcovr/gcovr#683] opened 2022-10-19 08:14 UTC
After I successfully executed `gtest`, I want to generate a single test coverage report via `gcovr`, but I get an error.
**In the company's secrecy system, I have hidden some files and path names.**
<details>
<summary>Exec Log</summary>
<pre>
(DEBUG) Finding source file corresponding to a gcov data file
  gcov_fname   /data00/home/${user_name}/repo/${repo_name}/vector.tcc##ef32c21a54bff2cef17e83196f1b4a56.gcov
  currdir      /data00/home/${user_name}/repo/${repo_name}
  root         /data00/home/${user_name}/repo/${repo_name}
  starting_dir /data00/home/${user_name}/repo/${repo_name}
  obj_dir      None
  gcda_fname   /data00/home/${user_name}/repo/${repo_name}/****/****/*****/*****.objs/src/be/******.cpp.gcno
  --> fname    /opt/tiger/cpp_tools/x86_64_x86_64_clang_1400/lib/gcc/x86_64-linux-gnu/11.2.0/../../../../include/c++/11.2.0/bits/vector.tcc
(DEBUG) Parsing coverage data for file /opt/tiger/cpp_tools/x86_64_x86_64_clang_1400/lib/gcc/x86_64-linux-gnu/11.2.0/../../../../include/c++/11.2.0/bits/vector.tcc
(DEBUG)   Filtering coverage data for file /opt/tiger/cpp_tools/x86_64_x86_64_clang_1400/lib/gcc/x86_64-linux-gnu/11.2.0/../../../../include/c++/11.2.0/bits/vector.tcc
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/workers.py", line 78, in worker
    work(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 337, in process_datafile
    done = run_gcov_and_process_files(
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 514, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 102, in process_gcov_data
    with io.open(
FileNotFoundError: [Errno 2] No such file or directory: '/data00/home/<stdin>##5877c01ccd0be143f73271645c2caa3d.gcov'
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/workers.py", line 78, in worker
    work(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 337, in process_datafile
    done = run_gcov_and_process_files(
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 514, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 102, in process_gcov_data
    with io.open(
FileNotFoundError: [Errno 2] No such file or directory: '/data00/home/<stdin>##5877c01ccd0be143f73271645c2caa3d.gcov'
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/gcovr", line 33, in <module>
    sys.exit(load_entry_point('gcovr==5.2', 'console_scripts', 'gcovr')())
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/__main__.py", line 317, in main
    covdata = collect_coverage_from_gcov(options)
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/__main__.py", line 369, in collect_coverage_from_gcov
    with Workers(
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/workers.py", line 171, in __exit__
    self.wait()
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/workers.py", line 162, in wait
    raise self.exceptions[0][1]
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/__main__.py", line 376, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/workers.py", line 162, in wait
    raise self.exceptions[0][1]
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/workers.py", line 78, in worker
    work(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 337, in process_datafile
    done = run_gcov_and_process_files(
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 514, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 102, in process_gcov_data
    with io.open(
FileNotFoundError: [Errno 2] No such file or directory: '/data00/home/<stdin>##5877c01ccd0be143f73271645c2caa3d.gcov'
</pre>
</details>
The strange thing is why there is a file prefixed with `stdin`?

gcovr version: 5.2
toolchain version: clang1400

**Comment by Spacetown** [comment] 2022-10-19 18:48
Are you running `gcov` with parallel jobs (`-j`)? The log is using `/data00/home/${user_name}/repo/${repo_name}/vector.tcc##ef32c21a54bff2cef17e83196f1b4a56.gcov` with currdir `/data00/home/${user_name}/repo/${repo_name}` but the exception is for `/data00/home/##5877c01ccd0be143f73271645c2caa3d.gcov` which is outside of your user directory.

**Comment by nolongerwait** [comment] 2022-10-20 02:05
> Are you running `gcov` with parallel jobs (`-j`)? The log is using `/data00/home/${user_name}/repo/${repo_name}/vector.tcc##ef32c21a54bff2cef17e83196f1b4a56.gcov` with currdir `/data00/home/${user_name}/repo/${repo_name}` but the exception is for `/data00/home/##5877c01ccd0be143f73271645c2caa3d.gcov` which is outside of your user directory.

Yep, I  ran `gcovr` with `-j 32`. 
But when I remove `-j`, it still has the same error.
<details>
<summary>Exec Log (without -j)</summary>
<pre>
(DEBUG) Parsing coverage data for file /opt/tiger/cpp_tools/x86_64_x86_64_clang_1400/lib/gcc/x86_64-linux-gnu/11.2.0/../../../../include/c++/11.2.0/type_traits
(DEBUG)   Filtering coverage data for file /opt/tiger/cpp_tools/x86_64_x86_64_clang_1400/lib/gcc/x86_64-linux-gnu/11.2.0/../../../../include/c++/11.2.0/type_traits
(DEBUG) Processing file: /data00/home/${user_name}/repo/${repo_name}/*****-bin/test.gcno
(DEBUG) Running gcov: '/opt/tiger/typhoon-*****/cpp_tools/x86_64_x86_64_clang_1400/bin/llvm-cov gcov /data00/home/${user_name}/repo/${repo_name}/*****-bin/test.gcno --branch-counts --branch-probabilities --demangled-names --hash-filenames --object-directory /data00/home/${user_name}/repo/${repo_name}/*****-bin' in '/data00/home/${user_name}/repo/${repo_name}'
(DEBUG) Running gcov: '/opt/tiger/typhoon-*****/cpp_tools/x86_64_x86_64_clang_1400/bin/llvm-cov gcov /data00/home/${user_name}/repo/${repo_name}/*****-bin/test.gcno --branch-counts --branch-probabilities --demangled-names --hash-filenames --object-directory /data00/home/${user_name}/repo/${repo_name}/*****-bin' in '/data00/home/${user_name}/repo/${repo_name}/*****-bin'
(DEBUG) Running gcov: '/opt/tiger/typhoon-*****/cpp_tools/x86_64_x86_64_clang_1400/bin/llvm-cov gcov /data00/home/${user_name}/repo/${repo_name}/*****-bin/test.gcno --branch-counts --branch-probabilities --demangled-names --hash-filenames --object-directory /data00/home/${user_name}/repo/${repo_name}/*****-bin' in '/data00/home/${user_name}/repo/${repo_name}'
(DEBUG) Running gcov: '/opt/tiger/typhoon-*****/cpp_tools/x86_64_x86_64_clang_1400/bin/llvm-cov gcov /data00/home/${user_name}/repo/${repo_name}/*****-bin/test.gcno --branch-counts --branch-probabilities --demangled-names --hash-filenames --object-directory /data00/home/${user_name}/repo/${repo_name}/*****-bin' in '/data00/home/${user_name}/repo'
(DEBUG) Running gcov: '/opt/tiger/typhoon-*****/cpp_tools/x86_64_x86_64_clang_1400/bin/llvm-cov gcov /data00/home/${user_name}/repo/${repo_name}/*****-bin/test.gcno --branch-counts --branch-probabilities --demangled-names --hash-filenames --object-directory /data00/home/${user_name}/repo/${repo_name}/*****-bin' in '/data00/home/${user_name}'
(DEBUG) Running gcov: '/opt/tiger/typhoon-*****/cpp_tools/x86_64_x86_64_clang_1400/bin/llvm-cov gcov /data00/home/${user_name}/repo/${repo_name}/*****-bin/test.gcno --branch-counts --branch-probabilities --demangled-names --hash-filenames --object-directory /data00/home/${user_name}/repo/${repo_name}/*****-bin' in '/data00/home'
(ERROR) Trouble processing '/data00/home/${user_name}/repo/${repo_name}/*****-bin/test.gcno' with working directory '/data00/home'.
Stdout of gcov was >>File '/data00/home/${user_name}/repo/${repo_name}/<stdin>'
Lines executed:0.00% of 1
No branches
No calls
Creating '<stdin>##5877c01ccd0be143f73271645c2caa3d.gcov'

<< End of stdout
Stderr of gcov was >>Permission denied
<< End of stderr
Current processed gcov file was '/data00/home/<stdin>##5877c01ccd0be143f73271645c2caa3d.gcov'.
Use option --verbose to get extended informations.
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/workers.py", line 78, in worker
    work(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 337, in process_datafile
    done = run_gcov_and_process_files(
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 514, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 102, in process_gcov_data
    with io.open(
FileNotFoundError: [Errno 2] No such file or directory: '/data00/home/<stdin>##5877c01ccd0be143f73271645c2caa3d.gcov'
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/workers.py", line 78, in worker
    work(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 337, in process_datafile
    done = run_gcov_and_process_files(
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 514, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 102, in process_gcov_data
    with io.open(
FileNotFoundError: [Errno 2] No such file or directory: '/data00/home/<stdin>##5877c01ccd0be143f73271645c2caa3d.gcov'
(ERROR) Uncaught EXCEPTION
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/gcovr", line 33, in <module>
    sys.exit(load_entry_point('gcovr==5.2', 'console_scripts', 'gcovr')())
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/__main__.py", line 317, in main
    covdata = collect_coverage_from_gcov(options)
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/__main__.py", line 369, in collect_coverage_from_gcov
    with Workers(
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/workers.py", line 171, in __exit__
    self.wait()
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/workers.py", line 162, in wait
    raise self.exceptions[0][1]
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/__main__.py", line 376, in collect_coverage_from_gcov
    contexts = pool.wait()
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/workers.py", line 162, in wait
    raise self.exceptions[0][1]
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/workers.py", line 78, in worker
    work(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 337, in process_datafile
    done = run_gcov_and_process_files(
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 514, in run_gcov_and_process_files
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/home/linuxbrew/.linuxbrew/Cellar/gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/gcov.py", line 102, in process_gcov_data
    with io.open(
FileNotFoundError: [Errno 2] No such file or directory: '/data00/home/<stdin>##5877c01ccd0be143f73271645c2caa3d.gcov'
</pre>
</details>

**Comment by Spacetown** [comment] 2022-10-20 05:13
Ok, now the output makes more sense. The `-j` should be used carefully because that are not real threads.

From this output it seems that your working directory is `/data00/home` and gcov brings a path relative to the current wd. Also a error `Permission denied` is printed.
Can you run gcovr from the directory where your compiler was called?

**Comment by nolongerwait** [comment] 2022-10-20 05:32
>  working directory is /data00/home

This is exactly what confuses me because I actually executed the `gcovr` from my repo directory `/data00/home/${user_name}/repo/${repo_name}/`. 

But I don't know why the current working directory will be changed.

Moreover, this morning, with the help of the rest of the company, we modified the code around `line 102` in the file `gcovr/5.2/libexec/lib/python3.10/site-packages/gcovr/gcov.py`. And finally successfully executed `gcovr` and generated the coverage report.

![pEIwzfNF8J](https://user-images.githubusercontent.com/22978131/196863439-7f7e65f4-dab7-419a-9680-bfd89f799cc4.png)

We have added a check for the input file name before the following code:
```python
#
# Process a single gcov datafile
#
def process_gcov_data(
    data_fname: str,
    covdata: CovData,
    gcda_fname: Optional[str],
    options,
    currdir=None,
) -> None:
#########
# Add checker
    if not os.path.isfile(data_fname):
        return
#########
    with io.open(
        data_fname, "r", encoding=options.source_encoding, errors="replace"
    ) as INPUT:
        lines = INPUT.read().splitlines()
```

**Comment by Spacetown** [comment] 2022-10-24 20:20
In following block the parent directories are added to the list of directories to try out.
https://github.com/gcovr/gcovr/blob/fc65655bd6c1de54a7a8ef31bc3d4674707e5fec/gcovr/gcov.py#L326-L336

Because of this in the log the WD contains all parent directories. Can you check in which directory the compiler is called?

**Comment by nolongerwait** [comment] 2022-10-25 09:44
work directory: `/data00/home/${user_name}/repo/${repo_name}/`
compiler directory(compile & test): `/opt/tiger/typhoon-*****/cpp_tools/x86_64_x86_64_clang_1400/`

Notably, I was able to find a file named `<stdin>##5877c01ccd0be143f73271645c2caa3d.gcov` in my working directory `/data00/home/${user_name}/repo/${repo_name}/` but it said `No such file or directory: /data00/home/<stdin>##5877c01ccd0be143f73271645c2caa3d.gcov` .

**Comment by Spacetown** [comment] 2022-10-29 19:06
Can you run the gcov command in the working directory and check if the gcov files are generated correct?

**Comment by nolongerwait** [comment] 2022-11-02 06:28
hi bro, ALL the issues ABOVE happened when I run `gcov` in the working directory.

**Comment by Spacetown** [comment] 2022-11-02 06:40
That's not a bug. `gcov` tries to find the correct directory. Did you run `gcov` without `r` in this directory? I'm interested in the output and the exit ode.

**Comment by Spacetown** [comment] 2022-11-02 07:03
BTW: What build system do you use? Are you running a cross compilation?

**Comment by nolongerwait** [comment] 2022-11-02 07:13
I misunderstood.

We are using a modified build system based on `[blade](https://github.com/chen3feng/blade-build)`. Our `.gcda`, `.gcno` and source files are not together. I might need to spend a little bit of an event here to understand how it works.

**Comment by Spacetown** [comment] 2022-11-02 07:21
Are the `gcno` files beside the `o` files? And the `o` files in different directories?

**Comment by nolongerwait** [comment] 2022-11-02 07:27
`.gcno`, `.gcda` and `.o` files are in the same directory.

but I cannot directly run `gcov` in this directory.

**Comment by nolongerwait** [comment] 2022-11-02 08:18
I have a question. Is the `test.cpp#xxxxxxxx.gcov` file generated by the `gcovr` command?

**Comment by nolongerwait** [comment] 2022-11-02 08:27
I checked all the files, including the third-party repo, and all the source files have the corresponding `.gcda`, `.gcno` and `.o` files except the single file `test.gcno`.

I can't find `test.o` nor `test.gcda` , and of course, I don't know where `test.cpp` or `test.h` are.

When I delete the abnormal `test.gcda`, all tasks are executed normally.

**Comment by nolongerwait** [comment] 2022-11-02 11:00
I think `gcovr` may be traversing the working directory to scan all the `.gxxx` (both `.gcda` and `.gcno`) files and generate `.gcov` files.

So what happens when there is only one `.gcno` file?

This single `test.gcno` file is generated by our build system, I will resolve this issue within the company.

But does `gcovr` consider the need to make a check for this case (to check whether the input file is valid or not) and give relevant error messages?

**Comment by Spacetown** [comment] 2022-11-02 20:00
> `.gcno`, `.gcda` and `.o` files are in the same directory.
> 
> but I cannot directly run `gcov` in this directory.

Why is this not possible?

> I can't find `test.o` nor `test.gcda` , and of course, I don't know where `test.cpp` or `test.h` are.
> 
> When I delete the abnormal `test.gcda`, all tasks are executed normally.

Is your executable called test? I guess if you call the compiler with several source files to link directly, the gcno is called like the executable.

> So what happens when there is only one `.gcno` file?

In this case gcov creates a report with zero coverage.

In https://gcovr.com/en/stable/guide/compiling.html the process and generation of the files is described.

**Comment by nolongerwait** [comment] 2022-11-03 03:09
> > .gcno, .gcda and .o files are in the same directory.
> > 
> > but I cannot directly run gcov in this directory.
> 
> Why is this not possible?
Because there is no useful information after execution.

> > I can't find test.o nor test.gcda , and of course, I don't know where test.cpp or test.h are.
> > 
> > When I delete the abnormal test.gcda, all tasks are executed normally.
> 
> Is your executable called test? I guess if you call the compiler with several source files to link directly, the gcno is called like the executable.

No, this `test.gcno` file is generated by our build system, and there is no `test` task or source file.

**Comment by nolongerwait** [comment] 2022-11-03 03:16
To check the file which causes python to throw the exception `FileNotFoundError`:
```bash
${user_name}@n248-144-119 /data00/home/${repo_path} cat '<stdin>##5877c01ccd0be143f73271645c2caa3d.gcov'
        -:    0:Source:/data00/home/${repo_path}/<stdin>
        -:    0:Graph:/data00/home/${repo_path}/blade-bin/test.gcno
        -:    0:Data:-
        -:    0:Runs:0
        -:    0:Programs:0
```

That's why I think the root cause is this lone `test.gcno`. I can reproduce this error in different projects.

**Comment by Spacetown** [comment] 2022-11-03 06:31
This looks like a unittests or another autogenerated file which is piped through stout to GCC. Please check your build system about this.
One solution can be to run gcov command on your own for the relevant files and collect the gcov files by running gcovr with the option `--use-gcov-files`.
I need to check if we can ignore files starting with `<stdin>` and generate a test for this.

**Comment by nolongerwait** [comment] 2022-11-03 06:39
> This looks like a unittests or another autogenerated file which is piped through stout to GCC. Please check your build system about this.

Yep, I have reported this issue of `test.gcno` to our internal build system team, and they will locate and fix it in the near future.

> One solution can be to run `gcov` command on your own for the relevant files and collect the gcov files by running `gcovr` with the option `--use-gcov-files`.

Since our build system is highly integrated with many commands, I may need to find out if the result of running `gcov` command by myself can be reported to the service in our company. Thank you for your suggestion.

> I need to check if we can ignore files starting with `<stdin>` and generate a test for this.

Thanks again.

**Comment by Spacetown** [comment] 2022-11-04 14:25
I can reproduce the error if I run the compiler in `/root/of/repo/build` but run `gcovr` in `/root/of/repo`.
With this, the following value is `true`. https://github.com/gcovr/gcovr/blob/c83215a72f6ca434df6b483627efe76d6d53145e/gcovr/gcov.py#L327 And the following block adds the parent directories until root. https://github.com/gcovr/gcovr/blob/c83215a72f6ca434df6b483627efe76d6d53145e/gcovr/gcov.py#L332-L336

If the directory is the same the files are handled correct even if piped from `stdin`.

**Comment by Spacetown** [comment] 2022-12-04 20:14
@nolongerwait Any progress on this?

**Comment by nolongerwait** [comment] 2023-02-09 05:50
There is currently no progress of value on this issue. There are still similar problems.

`(ERROR) Trouble processing '/data00/home/${user_name}/repo/${repo_name}/blade-bin/data/${x}/${x}.objs/src/${x}/fbthrift/server/FramingHandler.cpp.gcno' with working directory '/data00/home'.`

However, due to busy work, I haven't been able to devote energy to this issue yet.

And due to company tool limitations, we must run the compiler in `/root/of/repo/build` but run `gcovr` in `/root/of/repo`.

**Comment by Spacetown** [comment] 2023-02-14 20:48
@nolongerwait Then you should remove this limitation or produce the gcov files on your own and run `gcovr` with the option `--use-gcov-files` to pick up the files.
I've no idea how to get the correct directory if gcovr is called in the wrong directory. Maybe you can try `--object-directory=build`

**Comment by Spacetown** [comment] 2023-02-21 21:12
Closing issue since it's related to a limitation of the used build environment.

**Closed by Spacetown** 2023-02-21 21:12 UTC
Labels: Type: Question
