### ISSUE TITLE
gcovr 3.2 -r parameter containing spaces does not find source files

### ISSUE THREAD

**Issue by lemonkey** [gcovr/gcovr#141] opened 2016-08-25 19:43 UTC
If I simply use "." for the -r parameter value (root path), the coverage report detects the test case code properly. However if I point to the actual subfolder path of the main app source code, the report is always 0% because this subfolder path contains spaces. The value for -r is being wrapped in double quotes, e.g., "Some Path/Sub Folder"

Any advice?

**Comment by lemonkey** [comment] 2016-08-25 20:04
Escaping the space characters in the path has no effect btw.

**Comment by whart222** [comment] 2016-08-25 21:03
Work on a Linux box?  ;)

Let me see if I can replicate this error.  We should add a test case for
this!

Bill

**Comment by lemonkey** [comment] 2016-08-26 02:08
OS X :)

**Comment by whart222** [comment] 2016-08-26 18:32
Can you verify whether the master branch of gcovr works for you?  I just
added a new test, wspace, that works for the master branch.

**Comment by lemonkey** [comment] 2016-08-27 02:16
I'll take a look, thanks!

**Comment by lemonkey** [comment] 2016-08-29 19:35
The latest on master (3.3) doesn't fix the issue for me unfortunately.

**Comment by whart222** [comment] 2016-08-29 20:07
Can you give me more information about the path structure or help me modify the wspace test example to replicate this error?

**Comment by lemonkey** [comment] 2016-08-29 20:18
In this case, the project name nor the target have spaces, but the path to the actual source files at the root of the repo does. E.g., 

/usr/local/bin/gcovr3.3 "./DerivedData/Build/Intermediates/FooBar.build/Coverage-iphonesimulator/FooBar.build/Objects-normal/x86_64" -r "Foo Bar" -s -x -o "./cobertura/coverage.xml"

I've confirmed that the usual coverage files do exist in the above x86_64 path and a few of my other apps that are setup in the same way except for the source path not containing a space do successfully generate a report that has more than 0% coverage.

(FYI, this is for the latest Xcode 7 and the test scheme action does not have the Coverage checkbox checked)

**Comment by latk** [comment] 2018-02-11 20:28
I find this super mysterious, and I know of no good reason why this space should be a problem.

Can you verify whether the problem persists with the current development version of gcovr? (Sorry for asking you to do that again, but there have been some path- filtering-related changes since then.) If you can reproduce the problem, does the `--verbose` output shed any light on this? Are there any mentions of “Running gcov”? How many files are found after the “Scanning directory” message? Please show the relevant parts of the verbose output.

**Comment by latk** [comment] 2018-03-06 14:17
This issue has not seen any progress in a while, so I am closing it for now. If the problem persists, please add further details so it can be re-opened. If someone else is experiencing a similar issue, please create a new issue.

**Closed by latk** 2018-03-06 14:17 UTC
Labels: more info needed
