### ISSUE TITLE
Coveralls GitHub Action not supported.

### ISSUE THREAD

**Issue by zfields** [gcovr/gcovr#522] opened 2021-11-02 18:57 UTC
**Describe the bug**
The new Coveralls GitHub Action expects an ("LCOV file")[https://github.com/coverallsapp/github-action#usage]. The file created by `gcovr` is in some way incompatible with the Coveralls GitHub Action (error message below).

**To Reproduce**
Run `gcovr` with the `--coveralls` flag.

**Expected behavior**
A compatible format file is created.

**Error message**
```
Run coverallsapp/github-action@master
  with:
    github-token: ***
    path-to-lcov: ./coverage/lcov.info
    coveralls-endpoint: https://coveralls.io
Using lcov file: ./coverage/lcov.info
Error:  "2021-11-02T18:50:47.405Z"  'error from lcovParse: ' 'Failed to parse string'
Error:  "2021-11-02T18:50:47.405Z"  'input: ' '{"commit_sha": "5de684f7ba54e0529e2a911c6650a045417f0d3d", "run_at": "2021-11-02 18:50:46 UTC", "service_job_id": "Note Arduino CI", "service_name": "github-actions-ci", "service_number": "1413700493", "service_pull_request": "zak-coveralls", "source_files": [{"coverage": [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 98, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null], "name": "NoteI2c.hpp", "source_digest": "1d792469480400db18a4bcbddde55b87"}, {"coverage": [null, null, null, null, null, null, null, 7, null, null, null, null, 7, 3, 3, 3, null, 4, 3, null, 7, null, null, 35, null, null, 35, 35, null, 35, 35, null, null, 20, null, null, null, null, null, 20, 20, null, null, 45, 37, 37, 37, 37, null, null, 37, 12, null, null, 25, 10, 10, 10, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, null, null, null, null, 20, 12, 12, 12, 5, 7, 2, null, null, 5, null, 5, 2, null, 37, null, 34, null, null, null, null, null, 20, null, null, null, 3, null, null, null, null, 3, null, 3, 3, null, null, null, 8, null, null, null, null, 8, 8, null, 8, 8, 8, 8, null, 8, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, null, null, null, 8, null], "name": "NoteI2c_Arduino.cpp", "source_digest": "4c425b3de1bd54ddac266529404d83b0"}, {"coverage": [null, null, null, null, null, null, null, null, null, null, null, null, null, null, 16, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null], "name": "NoteLog.hpp", "source_digest": "121b13debcd4e683a67875f7a2486123"}, {"coverage": [null, null, null, 7, null, null, null, null, 7, 3, 3, 3, null, 4, 3, null, 7, null, null, 5, null, null, 5, 5, 5, null, null, 2, null, null, null, null, null, 2, null, 2, null], "name": "NoteLog_Arduino.cpp", "source_digest": "7887086bf6593d6a4a684bbb6c189828"}, {"coverage": [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 56, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null], "name": "NoteSerial.hpp", "source_digest": "12f9cb4ad0e33f694f1145051ea87d5e"}, {"coverage": [null, null, null, 7, null, null, null, null, null, 7, 3, 3, 3, null, 4, 3, null, 7, null, null, 18, null, null, null, 18, null, 18, null, 18, 18, null, null, 2, null, null, null, 2, null, null, null, 2, null, null, null, 2, null, null, null, 3, null, null, null, 3, null, 3, null, null, null, 6, null, null, null, null, null, null, 6, 6, 5, null, 6, null], "name": "NoteSerial_Arduino.cpp", "source_digest": "57d31b0a4c5deb9979759f9f89867002"}, {"coverage": [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 8, null, null, 8, null, 6, null, null, null, 2, null, 8, null, null, 5, null, null, 5, null, 3, null, null, null, 2, null, 5, null, null, 7, null, null, 7, null, 5, null, null, null, 2, null, 7, null, null, null, null, 5, null, null, 5, null, 3, null, null, null, 2, null, 5, null, null, null, null, 4, null, null, 4, null, 2, null, null, null, 2, null, 4, null, null, 4, null, null, 4, null, 2, null, null, null, 2, null, 4, null, null, 4, null, null, 4, null, 2, null, null, null, 2, null, 4, null, null, 5, null, 5, null, 4, null, 5, null, null, null, null, null, null, 85, null, null, 85, 85, 85, 85, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 34, null, 34, 34, 34, null, 34, null, 34, null, null, null, null, null, null, null, null, null, null, null, null, null, 28, null, 28, 28, 28, null, 28, null, 28, null, null, null, null, null, null, null, null, null, null, null, 6, null, 6, 6, 6, null, null, null, null, null, null, 1, null, 1, 1, null, null, null, null, null, null, null, null, null, null, null, 2, null, 2, null, null, null, null, null, null, null, null, null, null, null, null, 2, null, 2, null, null, null, null, null, null, null, null, null, null, null, null, null, 2, null, 2, null, null, null, null, null, null, null, null, null, null, null, null, 2, null, 2, null, null, null, null, null, null, null, null, null, 1, null, 1, 1, null, null, null, null, null, null, null, null, 1, null, 1, 1, null, null, null, null, null, null, null, null, null, 1, null, null, null, 1, 1, 1, 1, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, 3, null, 3, null, null, null, null, null, null, null, null, null, null, 2, null, 2, null], "name": "Notecard.cpp", "source_digest": "58141c623058da657d532570db2c2901"}]}'
Error:  "2021-11-02T18:50:47.406Z"  'error from convertLcovToCoveralls'
Error: Failed to parse string
```

**Comment by Spacetown** [comment] 2021-11-02 19:45
As documented the API format https://docs.coveralls.io/api-introduction is created by the option `--coveralls`. This file can be send with a simple POST to coveralls.io.

I've no idea what the best solution is.
1. Adding a option to generate the love format
2. Adding a GitHub Action which read and upload the data directly.

**Comment by zfields** [comment] 2021-11-02 21:26
GitHub actions are gaining a lot of traction.
1. Would be more difficult for this repository to maintain, because you can be broken by an external dependency.
2. Would require more upfront work to create (and maintain) a GitHub action, but it would make `gcovr` much more flexible and powerful.

**Comment by Spacetown** [comment] 2021-11-03 08:50
I think the first solution is easier to implement and and can be more useful. The format

**Comment by latk** [comment] 2021-11-03 10:34
This looks like an annoying issue! Thank you for reporting it. But I'd tend to agree with @Spacetown that this is not a bug, just a mismatch in expectations.

* Gcovr creates the Coveralls-JSON format.
* The Coveralls GH Action expects the Lcov-Info format.

Correspondingly, there are different ways to resolve this mismatch. On our end:

* We could change the meaning of `--coveralls`. That would be backwards-incompatible. ABSOLUTELY NOT.
* We could add support for generating the Lcov-Info format. This is a fantastic Wishlist item that could be implemented with reasonable effort. This would greatly improve gcovr because Lcov-Info files are very widely used.
* We could update our documentation to note that the Coveralls-JSON format cannot be consumed by the Coveralls GH Action. Might be a good idea, but we can't reasonably track the limitations of every downstream tool.

I do not think we could reasonably commit to maintaining a separate Coveralls uploader or a separate GH Action. Also, such actions or uploaders can be implemented by anyone and do not need specific support from the gcovr tool. I argued against embedding an uploader directly into gcovr in https://github.com/gcovr/gcovr/pull/328#issuecomment-529096328 on security grounds.

But perhaps the best way to fix this mismatch is at the *other end*: the Coveralls GH Action internally converts Lcov-Info to Coveralls-JSON. It should be straightforward to extend that action to optionally consume Coveralls-JSON directly.

I don't have time to do any of this, so:

* I'll create an issue as a reminder to implement Lcov-Info output one day.
* I'll close this issue as it does not indicate a bug in gcovr.
* I'll make sure that the docs are updated to avoid confusion when either the Coveralls-Action starts to support Coveralls-JSON or when gcovr starts to support Lcov-Info output.

**Closed by latk** 2021-11-03 10:34 UTC
Labels: Type: Enhancement
