### ISSUE TITLE
testpypi deployment fails (deprecated API)

### ISSUE THREAD

**Issue by latk** [gcovr/gcovr#197] opened 2018-01-18 10:22 UTC
Travis CI is configured to deploy the state of the master branch to testpypi. This is valuable to test the release process before doing an actual release. Unfortunately, this [doesn't work][travis-error]:

> Uploading distributions to https://testpypi.python.org/pypi
> Uploading gcovr-3.3-py2-none-any.whl
> HTTPError: 410 Client Error: Gone (This API has been deprecated and removed from legacy PyPI in favor of using the APIs available in the new PyPI.org implementation of PyPI (located at https://pypi.org/). For more information about migrating your use of this API to PyPI.org, please see https://packaging.python.org/guides/migrating-to-pypi-org/#uploading. For more information about the sunsetting of this API, please see https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html) for url: https://testpypi.python.org/pypi

  [travis-error]: https://travis-ci.org/gcovr/gcovr/jobs/330012531#L1239

The currently used .travis.yml states:

``` yml
deploy:
  - provider: pypi
    server: https://testpypi.python.org/pypi
    user: whart111
    password:
      secure: ...
    distributions: sdist --format=gztar bdist_wheel
    on:
      tags: false
      branch: master
      python: '2.7'
```

PyPI deployment from Travis CI is documented here: https://docs.travis-ci.com/user/deployment/pypi/
… but that doesn't shed any light on this problem :(

Would someone like to try fixing this? Because a pull request addressing this problem can't be tested before merging, please:

 - explain why the problem occurred,
 - explain why the pull request will fix this,
 - point to the relevant Travis and PyPI documentation, and
 - if possible, point to another project using the proposed solution, where upload demonstrably works.

I will then be happy to assist by reviewing, merging, and iterating proposed changes until this works.

**Comment by mayeut** [comment] 2018-01-19 00:10
https://github.com/gcovr/gcovr/blob/e44d17494296d0f8617230d6d6db02e3584a07e0/.travis.yml#L40

API endpoint shall be changed to `https://test.pypi.org/legacy/` c.f. https://packaging.python.org/guides/using-testpypi/#using-test-pypi

@latk, since you've got write access, you might want to commit in a new branch on this repo rather than yours (changing also the condition for deployment in `.travis.yml`). This will allow testing and prevent multiple commits in the master branch if this is not enough.

**Comment by latk** [comment] 2018-01-19 15:44
@mayeut Oh, thanks for digging up that part of the documentation. I'll try a test branch with your suggestions.

**Comment by latk** [comment] 2018-01-20 17:40
Thank you, that URL did in fact work. The test deployment uploaded the new universal wheel to test.pypi.org: https://test.pypi.org/project/gcovr/3.3/#files

Build log: https://travis-ci.org/gcovr/gcovr/jobs/331246871#L1245

Since this was released with the same version number, other files and the description were not updated. When the time for the next release comes, I'll have to remember to use a release-candidate version first.

Unless you can spot any further issues, I will update the testpypi URL directly on the master branch, without going through a PR.

**Comment by mayeut** [comment] 2018-01-21 12:45
Seems good to me.

**Comment by latk** [comment] 2018-01-30 17:29
To my horror the build failed again, this time because all artefacts that could be uploaded were already uploaded. This is no good because this marks the build on master as failed.

Proposed solution: test deployment failures are ignored, by adding

    allow_failure: true

This has the drawback that real failures will be ignored as well.

Alternatively, can the version be auto-incremented to something like `3.3-TIMESTAMP`? Or would that spam testpypi with unnecessary releases?

Another alternative: remove the testpypi deployment completely.

And thinking about releases more clearly, ordinary releases shouldn't be done from the master branch but a special release branch. I don't think the `on: branch: ...` condition can take regexes or patterns. So this would have to be a `on: condition: ...` Bash conditional?

**Comment by mayeut** [comment] 2018-01-31 07:14
I don't remember exactly if this is what drove me to using `twine` directly in one of my project. Python deployment in travis-ci does not offer support for the `--skip-existing` option of `twine`.
This option can also be useful if for whatever reason, upload fails between packages (I've seen this where a network issue caused only half of my wheels to be deployed, restarting the build would fail without the `--skip-existing` option)
c.f. travis-ci/travis-ci#7851

**Comment by latk** [comment] 2018-01-31 22:48
After having studied the PyPI [deployment prodiver source](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/pypi.rb#L92), it seems the most sensible approaches would either be to

 - perform deployment manually through twine, without using the existing Travis deployment provider, or
 - prepend a `twine` shim to the PATH that does `exec /path/to/real/twine "$@" --skip-existing`.

I think manual deployment is a lot less fragile, although care will have to be taken to not accidentally expose environment variable secrets. I'll try to fiddle around with this on the weekend, but of course I'll be happy if someone else finds a solution before me.

Or maybe there is a third possibility, such as patching the pypi deployment provider without having to wait for the patch to be deployed on Travis?

**Comment by latk** [comment] 2018-02-06 13:54
I have deactivated the testpypi deployment until a long-term solution can be found. After pondering the possible alternatives, I think that extending Travis' PyPI deployment provider is the best alternative.

I'm not very familiar with Ruby, so **help with this would be welcome**.

Concretely, we have the following tasks:

 - [ ] fork https://github.com/travis-ci/dpl and add a `skip_existing` option to `DPL::Provider::PyPI`.
 - [ ] in our .travis.yml, use the `edge` option to build with the forked provider (see https://github.com/travis-ci/dpl/blob/master/.github/CONTRIBUTING.md).
 - [ ] add unit tests to DPL, and open a pull request to upstream.
 - [ ] once DPL is deployed, update our .travis.yml to use the standard providers.

**Comment by mayeut** [comment] 2018-02-09 19:21
I thought of the same thing when digging around with travis-ci deployment options but did not had time to check until now. I'm not familiar at all with ruby but I thought I'd give it a try anyway.
I completed the 3 first tasks (well, 2nd one on my fork to be exact):
c.f. travis-ci/dpl#752

**Comment by latk** [comment] 2018-02-09 20:34
Thank you so much @mayeut  for looking into this :)
This is a tremendous help. Great work!

Can you update this issue once your PR is merged and live in Travis
production?

**Comment by mayeut** [comment] 2018-02-12 12:18
@latk, I will update the issue once the PR is merged. If you want, you can update gcovr .travis.yml file to deploy on edge using my fork of dpl in the meantime.

**Comment by mayeut** [comment] 2018-03-10 10:11
PR has been merged in travis-ci/dpl, release shall happen sometime next week.

**Closed** 2018-03-13 22:40 UTC
Labels: Type: Bug

**Comment by latk** [comment] 2018-03-22 21:51
@mayeut After merging #247 the TestPyPI [upload failed](https://travis-ci.org/gcovr/gcovr/jobs/356443677) again, do you have any insight why that might be?

```
Uploading distributions to https://test.pypi.org/legacy/
Uploading gcovr-3.4-py2.py3-none-any.whl
100%|██████████████████████████████████████| 44.3k/44.3k [00:00<00:00, 86.5kB/s]
HTTPError: 400 Client Error: The filename or contents already exist. See https://test.pypi.org/help/#file-name-reuse for url: https://test.pypi.org/legacy/
```

That looks like the `skip_existing: true` option is not registered? I don't see any obvious problem with the config…

**Comment by mayeut** [comment] 2018-03-22 22:19
Strange, https://travis-ci.org/gcovr/gcovr/builds/354991130?utm_source=github_status&utm_medium=notification passed skipping existing files.

dpl was version 1.9.1 vs now 1.9.5 but nothing changed in pypi deployment...
twine version 1.10.0 vs 1.11.0 but I can't figure out what changed that could break that...

**Comment by mayeut** [comment] 2018-03-30 22:46
@latk, I tracked the failure to  pypa/warehouse#3482

**Comment by latk** [comment] 2018-03-30 22:52
Oh wow, fantastic work! Thank you @mayeut for diving further into this
problem and opening the upstream bug :)

**Comment by mayeut** [comment] 2018-04-02 18:46
@latk, regression has been fixed in warehouse. If you restart the job, it shall succeed.

**Comment by latk** [comment] 2018-04-02 19:01
verified! The Travis badge in our readme shines in green glory once again :)
Thanks @mayeut for taking care of this issue!
