### ISSUE TITLE
ValueError on line 632, in process_gcov_data

### ISSUE THREAD

**Issue by psalvaggio** [gcovr/gcovr#272] opened 2018-07-16 14:43 UTC
Hello,

I ran into this issue on the RedHat Bugzilla:

https://bugzilla.redhat.com/show_bug.cgi?id=1567948

That I thought should be posted here. The stack I get is:
```
Writing directory view page.
Overall coverage rate:
  lines......: 86.2% (882 of 1023 lines)
  functions..: 55.6% (133 of 239 functions)
Traceback (most recent call last):
  File "/usr/bin/gcovr", line 2318, in <module>
    process_datafile(file_, covdata, options)
  File "/usr/bin/gcovr", line 897, in process_datafile
    process_gcov_data(fname, covdata, abs_filename, options)
  File "/usr/bin/gcovr", line 632, in process_gcov_data
    covered[lineno] = int(segments[0].strip())
ValueError: invalid literal for int() with base 10: '2*'
```
Seems like it's not stripping off that trailing *. Any ideas how to fix this issue?

**Comment by latk** [comment] 2018-07-16 15:00
Thank you for forwarding the report! However, that bug report seems to reference gcovr 3.3. The relevant code was significantly improved in versions 3.4 and 4.0, and I think we fixed a similar error.

Can the problem still be reproduced when the current release (4.1) is installed via pip? A simple `pip install gcovr` should do.

I'm closing this issue for now because it's likely to be fixed by updating gcovr, but I will of course reopen if the problem persists. In that case, I would also need the GCC version (gcovr-4.0 includes fixes for gcc 8) and the gcov file that led to the error.

**Closed by latk** 2018-07-16 15:00 UTC

**Comment by psalvaggio** [comment] 2018-07-16 15:44
I'll give that a try... I had been installing through `dnf` on Fedora, which still has 3.3.

**Comment by psalvaggio** [comment] 2018-07-16 15:53
That did the trick, thanks!
