### ISSUE TITLE
Merging coverage run options

### ISSUE THREAD

**Issue by decimad** [gcovr/gcovr#397] opened 2020-07-06 18:38 UTC
Hello there,
I hope I'm not addressing the wrong community. We're using gcovr to produce coverage stats for our library tests. Over the time test applications at different layers were developed, for which we seek to produce a merged coverage report of the one library they all test. Up to now, the applications would fetch the source-code of the library from the repo and build it in place in order to have the gcnos in place naturally. Now the natural course of action which should work in my eyes would be, to upgrade the build-system of the applications so one could configure them to use a central (yet still local) build of the library with gcov instrumentation. Then the runs should produce aggregated .gcdas and we're all fine. In my eyes this would be the right thing to do (tm) anyways, as this assures naturally that the same binary was tested.

Yet still I feel responsible to discover, whether there maybe is a way to merge coverage information from different build-trees of the same library (to pursue a quick an low-effort way in kinds), provided of course that the revisions and thus the sources match exactly. In my understanding of things, this would only be possible on the gcovr level of the processing tools, but I will gladly take be disproved.

Do you maybe have any advice in this regards?

**Comment by CezaryGapinski** [comment] 2020-07-07 19:02
Hi,
I don't know if it help you but gcovr has option to [merge coverage data](https://gcovr.com/en/stable/guide.html#combining-tracefiles) generated in JSON format, for example from different builds. 
IMHO the most straightforward way is to to run gcovr after your each run of your specific tests set to generate JSON output and after all builds merge the results with `--add-tracefile` option. There is an [example](https://github.com/gcovr/gcovr/tree/master/gcovr/tests/add_coverages) in tests directory how it is used to merge results when source code is built with different preprocessor defines, but I think you can also use in your idea.

There is a catch :). The JSON reports from different build to be correctly merged should be generated in the way to preserve the same relative paths to your source files (output reports should be generated from the same `root` directory).

**Comment by decimad** [comment] 2020-07-07 21:22
So I take if the build-trees look identical, because the directory setup of external dependencies for the individual test applications is structurally identical as well, then the individual jsons generated in the respective build roots should also be naturally compatible to be merged? This would indicate I can run a quick manual test without any real setup, this sounds great! I will give that a try, thank you!

**Comment by latk** [comment] 2020-07-08 10:06
What you're trying to do has not been tested yet, so I'd be interested to hear back about the results. But I think you can only merge JSON reports if they were created with the same `--root` option, and if you merge with the same `--root` setting as well.

The issue is this bit of code:

https://github.com/gcovr/gcovr/blob/39f5a82fb742300ea09adffa8f70b96a17f79061/gcovr/json_generator.py#L71-L73

To allow merging of arbitrary reports we would have to include the (absolute) root path into the JSON file, but I think that leads to more problems than it solves, such as complicating our testing. Are there alternatives for providing the JSON file's root path? The file path of the JSON file is not suitable because it could be moved around? Or should the file contain a relative path to the root, even though that might be fairly fragile (and impossible when crossing drive boundaries on Windows)?

The practical solution for your scenario would likely be to fix up the generated JSON reports before combining so that all paths are relative to the final project root you want. You can likely do that with a `jq` script.

**Comment by igagis** [comment] 2021-11-30 16:48
would that be possible to add a new feature to `gcovr` to supply what the root directory should be when generating JSON reports?

For example, if I have source files in `${root}/src/lib/*.cpp` and the lib was build with compiler and linker invoked from `${root}/src/`, then I could say:
```console
gcovr -r ${root}/src --base-dir ${root} --json > report1.json
```
so that the resulting `report1.json` would eventually contain paths relative to `${root}` instead of relative to `${root}/src`?
Then having binaries across different dirs we could generate JSON reports from the same `${root}` dir and then merge them?

**Comment by igagis** [comment] 2021-12-01 12:01
Actually, what is needed is to append (and perhaps canonicalize) the `root` directory, the one passed in as `-r` argument to file paths. Perhaps there could be a command line switch indicating that it needs to be done.

E.g.
```console
gcovr -r src --append-root --json > report1.json
```
would result in paths like `src/blabla.cpp` inside of the generated JSON.

Doesn't seem like a difficult feature to implement.

**Comment by latk** [comment] 2021-12-01 15:06
yes, something like a `--json-base` option sounds pretty sensible. I don't want to reuse the `--root` value because it already has multiple roles.

**Closed** 2022-08-20 19:57 UTC
Labels: Type: Question

**Comment by igagis** [comment] 2022-11-10 23:00
Thanks for implementing it!
But I think appending some base directory to file paths would also make sense for all other formats, like cobertura etc., not only for json.

**Comment by Spacetown** [comment] 2022-11-11 05:28
You should be able to merge the Jason with an appended base directory and run the HTML generation withe the merged file.
