### ISSUE TITLE
How to use gcovr when the source and object are in different directory. 

### ISSUE THREAD

**Issue by yqtianust** [gcovr/gcovr#545] opened 2021-12-27 15:37 UTC
I want to measure the code coverage of gcc. Here is my step:

1. Compile gcc. According to the manual of gcc, the `obj_dir` should be different from the `src_dir`. Therefore, I put the source code under `~/workspace/gcc`, and then I create a folder `~/workspace/obj_dir`. I configure the compilation under `~/workspace/obj_dir`, i.e., 
```bash
../gcc/configure --enable-coverage  --disable-multilib  --prefix=`pwd`/../gcc_8_5_0 --enable-languages=c,c++
make install
```

2. add the compiled gcc into my `PATH`, and invoke it to compile some source code.
3. call gcovr to measure the code coverage. 

In step 3, when I call gcovr under `~/workspace/`, i.e., `gcovr . --xml -o results.xml`, it gives me a lot of messages like the following:

```bash
(WARNING) GCOV produced the following errors processing /home/yq/workspace/obj_dir/gcc/cp/except.gcno:
        /home/yq/workspace/obj_dir/gcc/cp/except.gcda:cannot open data file, assuming not executed
Cannot open source file ../../gcc/gcc/vec.h
Cannot open source file ../../gcc/gcc/wide-int.h
Cannot open source file ../../gcc/gcc/poly-int.h
Cannot open source file gt-cp-except.h
Cannot open source file ../../gcc/gcc/cp/except.c
Cannot open source file cfns.gperf
Cannot open source file ../../gcc/gcc/tree-iterator.h
Cannot open source file ../../gcc/gcc/cp/cp-tree.h
Cannot open source file ../../gcc/gcc/cp/name-lookup.h
Cannot open source file ../../gcc/gcc/tree.h

        /home/yq/workspace/obj_dir/gcc/cp/except.gcda:cannot open data file, assuming not executed
Cannot open source file ../../gcc/gcc/vec.h
Cannot open source file ../../gcc/gcc/wide-int.h
Cannot open source file ../../gcc/gcc/poly-int.h
Cannot open source file gt-cp-except.h
Cannot open source file ../../gcc/gcc/cp/except.c
Cannot open source file cfns.gperf
Cannot open source file ../../gcc/gcc/tree-iterator.h
Cannot open source file ../../gcc/gcc/cp/cp-tree.h

...

        /home/yq/workspace/obj_dir/gcc/cp/except.gcda:cannot open data file, assuming not executed
Could not open output file '^#^#gcc#gcc#vec.h.gcov'
Could not open output file '^#^#gcc#gcc#wide-int.h.gcov'
Could not open output file '^#^#gcc#gcc#poly-int.h.gcov'
Could not open output file 'gt-cp-except.h.gcov'
Could not open output file '^#^#gcc#gcc#cp#except.c.gcov'
Could not open output file 'cfns.gperf.gcov'
Could not open output file '^#^#gcc#gcc#tree-iterator.h.gcov'
Could not open output file '^#^#gcc#gcc#cp#cp-tree.h.gcov'
Could not open output file '^#^#gcc#gcc#cp#name-lookup.h.gcov'
Could not open output file '^#^#gcc#gcc#tree.h.gcov'

        (gcovr could not infer a working directory that resolved it.)
```

Any step is wrong? 

I tried the command `gcovr obj_dir -r gcc --xml -o results.xml` but got the same message. 

In contrast, if I use `lcov --rc lcov_branch_coverage=1 --capture --directory ./obj_dir/ -o coverage1.info`, it does not throw these messages.

Thanks

**Comment by Spacetown** [comment] 2021-12-27 17:52
This messages come from `gcov` which is called internaly to transform the gcno and gcda files and not from `gcovr`.
If a gcda file is missing (code not executed) following message is printed:
```
...gcda:cannot open data file, assuming not executed
```
Following message is printed if a source file can't be opened by `gcov`:
```
Cannot open source file ...
```

For me it seems that the working directory for calling `gcovr` is wrong. The problem is, is the compiler called for every source file from the same directory? If not, you can try to run gcov for each gcda/gcno file from the correct directory and call afterwards `gcovr . --use-gcov-files --keep --xml -o results.xml`

**Comment by latk** [comment] 2021-12-27 19:25
This is the kind of use case where I fully recommend using lcov instead. Lcov has a very different architecture from gcovr, so it's not affected from this bug that gcovr has. Some relevant bugs have been fixed in gcovr 5.0, but it will still struggle with large projects that invoke gcc in creative ways.

Notes to self:
* implement gcov working-directory support (but won't fix this bug)
* implement gcov-json support (would probably fix this bug)
* implement support for lcov .info files as an input format (would be a workaround for this bug, and would greatly improve gcovr's usefulness)

**Comment by Spacetown** [comment] 2021-12-27 19:59
You can also use the option `-fprofile-abs-path` when compiling gcc as mentioned in #521.

**Comment by yqtianust** [comment] 2021-12-28 01:55
I will have a try. Thanks for your advice.

**Comment by latk** [comment] 2022-01-07 12:38
I'm closing this issue for now. While the solutions are a bit disappointing, there is nothing actionable that could be done to improve gcovr.

**Closed** 2022-01-07 12:38 UTC
Labels: Type: Question
