### ISSUE TITLE
gcovr parse error

### ISSUE THREAD

**Issue by igagis** [gcovr/gcovr#720] opened 2023-02-17 09:00 UTC
**Describe the bug**
Got a gecovr parse error when running gcovr:
```console
(WARNING) Unrecognized GCOV output for /__w/svgren/svgren/src/svgren/renderer.cpp
	  branch  6 taken -1
	This is indicative of a gcov output parse error.
	Please report this to the gcovr developers
	at <https://github.com/gcovr/gcovr/issues>.
```

**To Reproduce**
See github actions pipeline:
https://github.com/cppfw/svgren/actions/runs/4202112521/jobs/7289865543#step:12:20

**Expected behavior**
no error

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: linux
 - GCC version: not sure
 - GCOVR version: pip install git+https://github.com/gcovr/gcovr.git

**Additional context**
NA

**Comment by Spacetown** [comment] 2023-02-17 09:22
Duplicate of https://github.com/gcovr/gcovr/issues/583. This is a gcov bug and not related to gcovr.

**Closed by Spacetown** 2023-02-17 09:22 UTC
Labels: Type: Bug
