### ISSUE TITLE
lines considered as "non code"

### ISSUE THREAD

**Issue by goriy** [gcovr/gcovr#212] opened 2018-02-12 01:37 UTC
At the moment `gcovr` makes some addtional source code lines filtering to determine is the line contains code or not (for cases when gcov produces false positives?)

It's done by means of `is_non_code()` function. Particularly it filters out lines consist of single `}`, treat it as "non code".

I've got at least one case when it leads to errors in coverage calculations. I think it's very rare case.

There's some function which calls user function and kills running thread after that:
```C
static void thread_template (void *p)
{
  thread_data_t *dat = (thread_data_t *)p;
  dat->f();                /* call user function */
  (void)kill_thread(dat);  /* delete thread  */
}
```

Corresponding piece of gcov file looks like:
```gcov
function thread_template called 128 returned 0% blocks executed 100%
      128:  373:static void thread_template (void *p)
        -:  374:{
      128:  375:  thread_data_t *dat = (thread_data_t *)p;
      128:  376:  dat->f();                /* call user function */
call    0 returned 128
      128:  377:  (void)kill_thread(dat);  /* delete thread  */
call    0 returned 0
    #####:  378:}
```

Function `kill_thread` really never exits, so the end of `thread_template()` function is never executed. So, the statement coverage for that code could never be *100%*. `gcov` and some other coverage tools calculate it correctly, but `gcovr`, due to its `is_non_code()` function shows `100%` coverage. 

For this particular file `gcovr` shows:
```
------------------------------------------------------------------------------
File                                       Lines    Exec  Cover   Missing
------------------------------------------------------------------------------
../src/tmp.c                                 123     123   100%   
```

But `gcov` for the same file shows:
```
File '../src/tmp.c'
Lines executed:99.19% of 124
```

Cases like that are not very common, I suppose, so, there's no need to patch `gcovr` right now.

I think it needs to be discussed is there any sense to have additional "non code" filtration? Is there any real cases when `gcov` makes false positives in gcov files?

**Comment by Spacetown** [comment] 2022-08-10 19:54
Is the `kill_thread` a self written function?
I only find [pthread_kill](https://man7.org/linux/man-pages/man3/pthread_kill.3.html) and this function returns:
```
function thread_entry(void*) called 1 returned 100% blocks executed 100%
        1:    6:void* thread_entry(void* arg)
        -:    7:{
        1:    8:    pthread_detach(pthread_self());
        1:    9:    printf("Inside the thread\n");
        1:   10:    fflush(stdout);
        -:   11:
        1:   12:    pthread_kill(pthread_self(), 0);
        -:   13:
        1:   14:    return NULL;
        -:   15:}
```

Can you provide a small main.c to reproduce the issue?

**Comment by Spacetown** [comment] 2022-12-30 22:08
Closing because of missing response.

**Closed by Spacetown** 2022-12-30 22:08 UTC
Labels: Type: Bug

**Comment by Spacetown** [comment] 2022-12-31 10:35
I've checked the noreturn attribute of functions and I think it's correct to assume the closing brace as noncode. Gcov doesn't have a heuristic to filter out this lines and counts it.
