### ISSUE TITLE
Jekins Cobertura does not show  source code

### ISSUE THREAD

**Issue by AlexYIN** [gcovr/gcovr#207] opened 2018-01-31 03:17 UTC
Steps to reproduce: 

submit a Job to Jenkins, and wait for it to succeed 
(if Job is failing, fix the compilation and unit testing problem, and try again) 
visit Cobertura Coverage Report for daemon/table/fib.hpp 
Expected: the report displays the source code of daemon/table/fib.hpp, and highlights which lines are not covered by unit testing. 

Actual: 
Cobertura is unable to display painted source code when code coverage XML is generated from the Unix command line "gcovr -x" and the plugin configuration is set to correct xml report pattern. Error is:

Source code is unavailable. Some possible reasons are:

This is not the most recent build (to save on disk space, this plugin only keeps the most recent build's source code).
Cobertura found the source code but did not provide enough information to locate the source code.
Cobertura could not find the source code, so this plugin has no hope of finding it.
The code coverage XML data file is located in the same directory as the source file.
Note that the Trend diagram, Package Coverage Summary, File Coverage Summary, Class Coverage Summary display normally.

FYI. 
xml generated steps: 
cd daemon/table 
gcovr -r ./ --xml-pretty -s -o ./gcovr.xml 

the gcovr.xml head as below 
`SYSTEM 'http://cobertura.sourceforge.net/xml/coverage-03.dtd'> <coverage branch-rate="0.0132740135658" line-rate="0.0193204762236" timestamp="1517384737" version="gcovr 3.3"> <sources> <source>./</source> </sources> <packages>`

gcovr version: 3.3 
cobertura version: 1.11

**Comment by latk** [comment] 2018-01-31 07:47
This may be a duplicate of #177. Please try the following steps:

 - Invoke gcovr in the root of your project, so that Cobertura can resolve the relative paths. I think in your case, the XML contains `./fib.hpp` so Cobertura is looking for `the-project/fib.hpp` not for `the-project/daemon/table/fib.hpp` (relative paths are not resolved relative to the XML file). An invocation like this might work:

        gcovr -r daemon/table -x -s -o daemon/table/gcovr.xml

 - If that doesn't work, simply invoke gcovr with an absolute root path:

        cd daemon/table
        gcovr -r `pwd` -x -s -o gcovr.xml

Did one of these approaches work?

**Comment by AlexYIN** [comment] 2018-02-02 01:27
@latk  I move all the *.h and *.cpp to the root directory of project named myProject
and run the  command as below:
`cd ~/myProject
both 
gcovr -r `pwd` -x -s -o gcovr.xml
or 
gcovr -r ./ -x -s -o `
will got error as below:

java.lang.SecurityException: agent may not mkdirs /var/lib/Common/DA/inc
See https://jenkins.io/redirect/security-144 for more details
	at jenkins.SoloFilePathFilter.noFalse(SoloFilePathFilter.java:31)
	at jenkins.SoloFilePathFilter.mkdirs(SoloFilePathFilter.java:52)
	at hudson.FilePath.mkdirs(FilePath.java:2923)
	at hudson.FilePath.access$800(FilePath.java:197)
	at hudson.FilePath$13.invoke(FilePath.java:1162)
	at hudson.FilePath$13.invoke(FilePath.java:1159)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2749)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:336)


Seems that directory matching got something wrong.

**Comment by latk** [comment] 2018-02-02 09:46
That error originates from Jenkins, not from gcovr. The Jenkins
Security-144 policy prevents a build slave process from manipulating files
on the Jenkins master server. However, gcovr is not a Jenkins plugin and
therefore cannot not issue such commands. Maybe this error occurs while you
are copying files back to the master server? I'm afraid this isn't the
right place for support with Jenkins problems :/

Can you run gcovr manually first? Once we've verified that the gcovr
command produces the expected output, it should be easier to get the
Jenkins part working.



2018-02-02 2:27 GMT+01:00 AlexYIN <notifications@github.com>:

**Comment by latk** [comment] 2018-02-09 20:37
This issue has not seen any progress in a while, so I am closing it for now. If the problem persists, please add further details so it can be re-opened. If someone else is experiencing a similar issue, please create a new issue.

**Closed by latk** 2018-02-09 20:37 UTC
