### ISSUE TITLE
gcovr doesn't create detailed report when source file are located in other directories

### ISSUE THREAD

**Issue by milexy86** [gcovr/gcovr#112] opened 2015-08-20 14:33 UTC
Hi,

if for example my source files are located within source/myfile.c and the gcda and gcno files also within obj/ , than gcovr creates me the detailed html report  -  everything OK. 

Problem is when I have to take the source files for example from:
../../../Project/Common/Source/myfile.c , than the main html report with the summary is created, but not the detailed one of my source file "myfile.c" . 

The gcovr command is:

C:\Python34\Scripts\gcovr -v -b -r C:\Project\UnitTests\myModule\module1 --object-directory      C:\Project\UTests\myModule\module1\test-obj\Common\Source --html --html-details -o report\report.html

For better understanding, I have attached a screenshot. You see, the main html is generated, butt not the one for "myfile.c" (When i click on myfile.c to see the detailed report, I'm not relinked to it, because it doesn't exist). 

Any idea?
![gcovr_result](https://cloud.githubusercontent.com/assets/13888058/9385879/130476f4-4759-11e5-8802-d00690fe4111.PNG)

**Comment by AndersHoglund** [comment] 2016-01-11 21:57
I have a similar problem, and I have found some workarounds that might help.
1. Use the latest gcovr version on the dev branch.
2. Replace all relative parallell paths in buildscripts/makefiles with symlinks in the filesystem. 
3. Run gcovr twice. First time with "-k" option, second time with "-k -g" options. I also add "-x" for xml output in the last stage.

For example in my Makefile I do this:

    # Workaround limitations in gcovr. .
    # Replace relative path with a symlink "main -> ../main"
    #USER_DIR := ../main
    USER_DIR := main

And the Jenkins job does this:

    /home/andho/projects/coverage/gcovr/scripts/gcovr -r obj/test/ -k
    /home/andho/projects/coverage/gcovr/scripts/gcovr -r obj/test/ -k -g -x > coverage.xml

Hope it is some help....

**Comment by AndersHoglund** [comment] 2016-01-12 17:07
Found another way way to run gcovr, without symlinks and just run once.
You can supply your coverage data location as a pure arg (no option) and point the root to your sources.

     /home/andho/projects/coverage/gcovr/scripts/gcovr obj/test --root=src/main -x > coverage.xml

Found this out by reading the sources, supplying an arg like that is not documented in the --help text.

**Comment by nickbroon** [comment] 2016-01-18 21:49
I think this is perhaps a duplicate of #61

**Comment by nickbroon** [comment] 2016-01-18 22:09
@AndersHoglund suggested work around doesn't appear to work when object directory is a subdirectory of the src directory. ie something like:
`gcovr obj-x86_86 --root=. -x > coverage.xml`

**Comment by AndersHoglund** [comment] 2016-01-18 22:32
Well, if the object dir is a subdir under your root then everything is as assumed by gcovr. Should not need so say anything, it would find the objects, coverage data and sources automatically. Problems occurs when sources and objects are on different paths. But it is all a bit confusing, I did a lot of T&E and only stumbled on some combos that seemed to work, without really understanding why. And I read the sources trying to understand the implicit meaning of some things. Some strict definitions and structuring of what "root", "start_dir", "object_directory" etc actually means would be good. There is for example no "source_dir", it is assumed to relate to something else. And this may not always be true...

**Comment by nickbroon** [comment] 2016-01-19 10:51
I made the following change to the oos testcase, such that I believe it more closely reflects how tools like autoconf/automake perform out of source builds (what they call vpath builds), and it fails:

```diff
diff --git a/gcovr/tests/oos/Makefile b/gcovr/tests/oos/Makefile
index a679d80..b5d5eb9 100644
--- a/gcovr/tests/oos/Makefile
+++ b/gcovr/tests/oos/Makefile
@@ -1,14 +1,14 @@
 CFLAGS= -fprofile-arcs -ftest-coverage -fPIC
 
 all:
-       mkdir -p build
-       $(CXX) $(CFLAGS) -c src/file1.cpp -o build/file1.o
-       $(CXX) $(CFLAGS) -c src/main.cpp -o build/main.o
-       $(CXX) $(CFLAGS) build/main.o build/file1.o -o build/testcase
+       mkdir -p build/src
+       cd build; $(CXX) $(CFLAGS) -c ../src/file1.cpp -o src/file1.o
+       cd build; $(CXX) $(CFLAGS) -c ../src/main.cpp -o src/main.o
+       cd build; $(CXX) $(CFLAGS) src/main.o src/file1.o -o testcase
 
 run: txt xml html
 
-GCOVR_TEST_OPTIONS = -r '.'
+GCOVR_TEST_OPTIONS = -v -r '.'
 
 txt:
        build/testcase
@@ -23,5 +23,5 @@ html:
        ../../../scripts/gcovr $(GCOVR_TEST_OPTIONS) -d --html --html-details -o coverage.html
 
 clean:
-       rm -f build/*
+       rm -rf build/*
        rm -f coverage.txt coverage.xml coverage*.html
```

```
======================================================================
FAIL: test_oos (__main__.GcovrTxt)
function test: test_oos (__main__.GcovrTxt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyutilib/th/pyunit.py", line 256, in <lambda>
    func = lambda self,c1=fn,c2=name,c3=suite: _run_fn_test(self,c1,c2,c3)
  File "/usr/local/lib/python2.7/dist-packages/pyutilib/th/pyunit.py", line 164, in _run_fn_test
    explanation = fn(self, name)
  File "test_gcovr.py", line 92, in gcovr_test_txt
    self.assertFileEqualsBaseline("coverage.txt", "reference/coverage.txt")
  File "/usr/local/lib/python2.7/dist-packages/pyutilib/th/pyunit.py", line 224, in assertFileEqualsBaseline
    self.fail("Unexpected output difference at line "+str(lineno) +":\n   testfile="+testfile+"\n   baseline="+baseline+"\nDiffs:\n"+diffs)
AssertionError: Unexpected output difference at line 7:
   testfile=coverage.txt
   baseline=reference/coverage.txt
Diffs:
--- reference/coverage.txt

+++ coverage.txt

@@ -1,5 +1,5 @@

 File                                       Lines    Exec  Cover   Missing
 ------------------------------------------------------------------------------
-src/file1.cpp                                  2       2   100%
-src/main.cpp                                   8       7    87%   7
 ------------------------------------------------------------------------------
+TOTAL                                          0       0    --%
+------------------------------------------------------------------------------

======================================================================
```

**Comment by latk** [comment] 2018-02-11 13:58
There have been a lot of improvements recently, especially for Windows. Can you check whether the issues still occur with the development version of gcovr?

I am closing this issue for now. If the problem persists, please add further details so it can be re-opened. If someone else is experiencing a similar issue, please create a new issue.

**Closed by latk** 2018-02-11 13:58 UTC
Labels: Format: HTML, Platform: Windows, Type: Bug

**Comment by barthoukes** [comment] 2018-05-03 13:05
Still problems, feel free to use the fork on https://github.com/barthoukes/gcovr where issues were solved (quick/dirty but working)
