### ISSUE TITLE
Line numbers reported incorrectly

### ISSUE THREAD

**Issue by 0ge** [gcovr/gcovr#345] opened 2019-12-06 15:44 UTC
I'm getting some unreasonable line numbers reported from `gcovr`/`gcov`. (I don't know the culprit or how to find out)
For instance, there is the following entry in the xml output:

```
<class name="MyClass_h" filename="src/Subfolder A/MyClass.h" line-rate="0.666666666667" branch-rate="0.5" complexity="0.0">
  <methods/>
  <lines>
  ...
   <line number="180" hits="0" branch="false"/>
   <line number="182" hits="0" branch="false"/>
   <line number="183" hits="0" branch="false"/>
   <line number="184" hits="0" branch="false"/>
   <line number="187" hits="0" branch="false"/>
 </lines> 
</class>
```

However, the file "src/Subfolder A/MyClass.h" is only 180 lines. In this case its a template class.
There are some other instances where there is line coverage reported on comment lines, etc. as well.

If I view the HTML file it shows the correct source.

I guess I'm doing something wrong, but I can't figure out what?

Execution from root:
```
c++ -Isrc -isystema/folder -DA_DEFINE -Wall -funsigned-char -std=c++11 -fprofile-arcs -ftest-coverage -O1 -g3 -fno-inline -fno-omit-frame-pointer -fno-optimize-sibling-calls -c -o build/test/obj/Subfolder/Class.o src/Subfolder/Class.cpp

gcovr --object-directory build/test/obj -e "(vendor*)|(test_*)|(src/Bsp/*)|(build/test*)" --branches -p  --html --html-details -o build/reports/html/coverage.html build/test/obj
gcovr -r ./ --object-directory build/test/obj -e "(vendor*)|(test_*)|(build/test*)" --branches -p --xml-pretty -o build/reports/coverage.xml build/test/obj
```

Project layout:
```
├── build
│  ├── reports
│  │  └── html
│  └── test
│     └── obj
│        ├── Subfolders with object files and .gcno/.gcda files (sources)
│        └── Object files and .gcno/.gcda files (tests)
├── src
│  ├── Subfolder A
│        └── Source and header files
│  └── Subfolder B
│        └── Source and header files
├── test
│  └── Test files (google test)
└── vendor
   └── 3rd party libraries
```

Environment:
```
macOS 10.15.1
gcovr 4.2
Apple clang version 11.0.0
```

**Comment by latk** [comment] 2019-12-06 16:10
Sometimes gcovr gets confused when you have multiple header files with the same name, e.g. `A/myheader.h` and `B/myheader.h`. Could that be the case here?

Gcovr's `--object-directory` option usually doesn't help. It was an attempt to fix this problem, but it's more of a bandaid. Do you get the problem with and without this option?

Additional notes:

* when using Clang you must set the `--gcov-executable` option or `GCOV` environment variable, presumably to `llvm-cov gcov`
* your exclude filter should work, but doesn't look quite correct. The filter takes a regex and not a glob pattern, so that the `*` operator means “match the previous character multiple times”. To match any character you have to use `.*`, but doing so is not necessary at the end of the filter. Using multiple filters works as well, so you could do: `-e vendor/ -e 'test_.*' -e src/Bsp/`. A filter to explicitly clearlist might be easier, e.g. `-f 'src/Subfolder (A|B)/'`
* with gcovr 4.2 you can create multiple reports in one go, e.g. `gcovr -p --html-details build/reports/html/coverage.html --xml build/reports/coverage.xml`

**Comment by 0ge** [comment] 2019-12-09 08:43
Thanks for the reply!

There is one filename that appears twice, but its not included (directly or indirectly) by the file in question.
I do get the same output with or without `--object-directory`.

Much appreciate the notes. It cleaned up the Makefile quite a bit. One question though: if I run `gcov --version` I get `Apple LLVM version 11.0.0 (clang-1100.0.33.12)`. Do I still need the `--gcov-executable`?

**Comment by latk** [comment] 2019-12-11 11:10
Hmm, that is odd and I don't have an explanation right now. If it would be possible to boil down your project to a minimal reproducible example I could try to take a look. I.e. create a new branch of the project and iteratively remove parts that are not necessary for reproducing the bug.

It could be that this is due to Clang-specific behaviour, because our test suite is specific to an ancient GCC version. Clang-based tests are still a wishlist item (#134).

If your `gcov` tool is actually from Clang, then you don't have to set the `--gcov-executable` option. Everything should work by default.

**Comment by 0ge** [comment] 2019-12-11 12:55
Unfortunately, I cannot share the project. (Proprietary)
I will see if I can find the time to reproduce the issue on a test project.

I did run the same project with the same commands in a different environment. That helped.
```
Ubuntu 16.04.4 LTS
gcovr 4.2
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
```

This gives expected results. (No weird line numbers, etc)

Maybe related to template instantiation?

**Comment by latk** [comment] 2019-12-11 20:55
That indicates gcovr isn't interpreting the clang-gcov output correctly, or that the Mac's file name handling is somehow getting in our way. Templates are unlikely to be at fault here, but anything is possible.

If you ever get around to isolating a reproducible example that would be great, and I fully understand that you can't share proprietary code. However, stripping down a real project is often easier than reproducing the issue from scratch.

**Comment by Spacetown** [comment] 2020-07-27 21:26
We had the same problem with a static code analysis tool. This was a result of mixed line endings (Windows and Unix) and the line counters had wrong values.
Or maybe there is a old gcno/gcna file where a old version of the header was used.

**Comment by dsakilesh** [comment] 2021-03-09 13:02
Hi @latk 

We have also faced similar issue with no solution yet.

GCC version = 9.2.1
gcovr 4.2

We tried 
* .gitattributes approach to fix the line endings but no luck
* checked if it contains multiple files with same name and the answer is No
* there are no old gcno/gcna files available

Please help here. Thanks in advance!

**Comment by Spacetown** [comment] 2021-03-09 19:45
@dsakilesh Can you reproduce the problem on a test project and share the files?

**Comment by dsakilesh** [comment] 2021-03-17 06:43
Hi @Spacetown @latk 

Paths in the Sonarqube.xml are starting from different directories(Reference: https://github.com/gcovr/gcovr/issues/478 ) and they do not have a common path. To align the paths we have used **--root** option in gcovr command to resolve the paths in sonarqube.xml.

After we have used **--root** option we have "line out of range in file" issue. Without **--root** option the build directory does not get picked up( Reference: https://github.com/gcovr/gcovr/issues/478)

**Comment by Sidelobe** [comment] 2021-03-17 08:29
I have a similar problem in my project: some line numbers are wrong (e.g. higher than number of lines in file), which causes Sonarqube to reject the report (running this locally).
Amusingly, I'm also running gcovr on CI  (Azure devops) and feeding cobertura-style reports (`--xml`) to the Azure pipeline and it does not complain. I'm guessing it is filtering out the invalid lines?

* HTML reports work fine
* Other XML reports exhibit the same behavior
* Unlike @dsakilesh, I do have absolute paths for all files in my XML reports
* I've tried building in both Release & Debug, doesn't seem to help

My Gcovr build command: [run from deploy/build/sonarqube]:
`gcovr -r ../.. -f ../../../source --exclude-unreachable-branches --exclude-throw-branches --sonarqube -o report/coverage.xml`

Other data:
* I'm on macos, running gcvor 4.2, using bash shell
* Compiling with Clang (Apple clang version 11.0.3 (clang-1103.0.32.62)
* My project uses both C++ and C (and some preprocessor macro functions... which I somehow suspect).

Unfortunately I can't share my project either, but I'll try to strip it down until I have a minimal reproducible example without IP.

**Comment by dsakilesh** [comment] 2021-03-17 09:04
[sonarqube-debug-log.txt](https://github.com/gcovr/gcovr/files/6155002/sonarqube-debug-log.txt)
Unfortunately i can't share the project so attaching debug logs

**Comment by Spacetown** [comment] 2021-03-18 18:52
@dsakilesh @Sidelobe I can't reproduce it. Is it possible for you to run gcovr with the option `--keep` and search the gcov files containing data for the erroneous file.

Search the text `function ` backward from the end and check the line number (next line in front of the double colon).
Compare this number to the line numbers in the text editor.
You can also check if the code of the lines from the error message are in sync with the code in the text editor.

E.g. function main should start in line 18:
https://github.com/gcovr/gcovr/blob/60873159db811ce13add978e1d9c8b52752c6022/gcovr/tests/test_gcov_parser.py#L71-L76

**Comment by dsakilesh** [comment] 2021-03-19 09:13
Hi @Spacetown @latk 

It is clearly working fine without **--root ${workspace}** option. After we add this option to the feature branch to correct the build coverage path issue we encounter this issue. So we feel that its not a code issue.

Could you check from your side if this **--root** option is doing anything additional to changing the coverage file path in xml?

For example: _src/src/Util/Version.cpp_ file only contains **65** lines but the sonarqube contains coverage metrics upto **396th** line.
`<file path="src/src/Util/Version.cpp"><lineToCover lineNumber="27" covered="true"/><lineToCover lineNumber="33" covered="true"/><lineToCover lineNumber="34" covered="true"/><lineToCover lineNumber="37" covered="true"/><lineToCover lineNumber="40" covered="true" branchesToCover="6" coveredBranches="6"/><lineToCover lineNumber="41" covered="true"/><lineToCover lineNumber="42" covered="true"/><lineToCover lineNumber="43" covered="true" branchesToCover="6" coveredBranches="6"/><lineToCover lineNumber="44" covered="true"/><lineToCover lineNumber="46" covered="true"/><lineToCover lineNumber="48" covered="true" branchesToCover="6" coveredBranches="6"/><lineToCover lineNumber="49" covered="true"/><lineToCover lineNumber="50" covered="true"/><lineToCover lineNumber="51" covered="true"/><lineToCover lineNumber="52" covered="true"/><lineToCover lineNumber="55" covered="true"/><lineToCover lineNumber="56" covered="true"/><lineToCover lineNumber="58" covered="true"/><lineToCover lineNumber="59" covered="true"/><lineToCover lineNumber="60" covered="true" branchesToCover="2" coveredBranches="1"/><lineToCover lineNumber="61" covered="true"/><lineToCover lineNumber="156" covered="false"/><lineToCover lineNumber="157" covered="true"/><lineToCover lineNumber="158" covered="true"/><lineToCover lineNumber="159" covered="true"/><lineToCover lineNumber="174" covered="false"/><lineToCover lineNumber="192" covered="false"/><lineToCover lineNumber="203" covered="true" branchesToCover="8" coveredBranches="3"/><lineToCover lineNumber="204" covered="true"/><lineToCover lineNumber="339" covered="false"/><lineToCover lineNumber="396" covered="true" branchesToCover="2" coveredBranches="1"/>`

As mentioned earlier we have tried all possible things from our side. 
Looking forward for your response.

**Comment by Spacetown** [comment] 2021-03-20 19:40
I've tried the layout on Mac with clang and gcov but I can't reproduce it.
Apple clang version 11.0.0 (clang-1100.0.33.17)

For me the option --root only affects the path in the report.

@dsakilesh Can you try to rename the file `src/src/Util/Version.cpp` in e.g `rc/src/Util/Version_x.cpp` to exclude duplicate names?

**Comment by Sidelobe** [comment] 2021-03-21 11:36
I've tried to strip down my project, but I cannot seem to reproduce the error state at all anymore (even after going back in Git history). It must have been some caching/data issue - even though I'm certain I was deleting all `.gcno` and `.gcda` files and all other data between runs.

While this is good news for me (my project is working again), I'm afraid this makes my contributions to this thread less valuable :-/
I'll keep an eye open and isolate it as soon as/if I  find it again.

**Comment by dsakilesh** [comment] 2021-03-25 08:11
@Spacetown 

I have renamed the file and updated the dependent files. I still face the same issue.

We also have one repository where there is line endings issue even though we are not using the **--root ${workspace}** option.

As it is looking more and more like gcovr issue with xml generation, is it a good option, to generate json (instead of xml) and then convert the json to xml before doing the sonar-scan?

**Comment by dsakilesh** [comment] 2021-03-25 10:09
Hi @Spacetown 

We tried the json format in gcov command and we still have the additional coverage metric values in json format, same as xml output.

This is not happening for the html. Its works like expected with out any issues.

Command used for gcov:
`python -m gcovr --gcov-executable="llvm-cov gcov" -v --branches -f '${workspace}/${buildDir}/(src|include)/' -f '${path.src}/(src|include)/' --object-dir=. --html-details=gcovreport/index.html --sonarqube=gcovreport/sonarqube.xml --json gcovreport/sonarqube.json`

PFA the json, xml and html reports.
[sonarqube.json.txt](https://github.com/gcovr/gcovr/files/6203807/sonarqube.json.txt)
[sonarqube.xml.txt](https://github.com/gcovr/gcovr/files/6203808/sonarqube.xml.txt)
[HTML_version_cpp.html.txt](https://github.com/gcovr/gcovr/files/6203810/HTML_version_cpp.html.txt)

**Comment by Spacetown** [comment] 2021-03-25 18:36
@dsakilesh The HTML is working because the lines of the file are read.
https://github.com/gcovr/gcovr/blob/24aa534d143721588456ee82f999c3a3cb22a65c/gcovr/writer/html.py#L398-L404
The coverage is assigned to the lines and the template iterates through the lines.
https://github.com/gcovr/gcovr/blob/24aa534d143721588456ee82f999c3a3cb22a65c/gcovr/templates/source_page.html#L55

I can try to provide you a test branch with print statements for `Version.cpp`. Maybe this will help to find the root cause.

**Comment by Spacetown** [comment] 2021-03-25 19:39
@dsakilesh Can you test the branch version with additional option `--verbose`?
Inerresting are the parts starting with `Reading file ...Version.cpp` including the lines from the gcov file (line 60 to 80 are printed). Does the content of the gcov file matches to the source code of Version.cpp or is it different?

**Comment by dsakilesh** [comment] 2021-04-06 08:57
Hi @Spacetown 

We have made the changes which are suggested in the https://github.com/Spacetown/gcovr/commit/a289025412270bfd7bd7a3dcdd5ff19a0319f9e2 commit and have attached the logs output.

[gcov-command-version-cpp.txt](https://github.com/gcovr/gcovr/files/6263386/gcov-command-version-cpp.txt)

Please check. Thanks in advance!

**Comment by Spacetown** [comment] 2021-04-06 19:48
@dsakilesh I've checked the log and I think I've found the problem. Here are the interested lines:
[gcov-command-version-cpp.txt](https://github.com/gcovr/gcovr/files/6267098/gcov-command-version-cpp.txt)

There are several Version.cpp.gcov analyzed in the log:
```
Processing file: /var/jenkins/0/workspace/_feature_align-coverage-metrics2/build/unittest-clang/BRC36xx-5/Debug/src/Util/CMakeFiles/Util.dir/Version.cpp.gcno
Running gcov: 'llvm-cov gcov /var/jenkins/0/workspace/_feature_align-coverage-metrics2/build/unittest-clang/BRC36xx-5/Debug/src/Util/CMakeFiles/Util.dir/Version.cpp.gcno --branch-counts --branch-probabilities --preserve-paths --object-directory /var/jenkins/0/workspace/_feature_align-coverage-metrics2/build/unittest-clang/BRC36xx-5/Debug/src/Util/CMakeFiles/Util.dir' in '/tmp/tmp4j6_phqh'
```
```
Processing file: /var/jenkins/0/workspace/_feature_align-coverage-metrics2/build/unittest-gcc/BRC36xx-5/Release/test/Util/CMakeFiles/Util-Test.dir/__/__/src/Util/Version.cpp.gcda
Running gcov: 'llvm-cov gcov /var/jenkins/0/workspace/_feature_align-coverage-metrics2/build/unittest-gcc/BRC36xx-5/Release/test/Util/CMakeFiles/Util-Test.dir/__/__/src/Util/Version.cpp.gcda --branch-counts --branch-probabilities --preserve-paths --object-directory /var/jenkins/0/workspace/_feature_align-coverage-metrics2/build/unittest-gcc/BRC36xx-5/Release/test/Util/CMakeFiles/Util-Test.dir/__/__/src/Util' in '/tmp/tmp4j6_phqh'
```
```
Processing file: /var/jenkins/0/workspace/_feature_align-coverage-metrics2/build/unittest-gcc/BRC36xx-5/Release/src/Util/CMakeFiles/Util.dir/Version.cpp.gcno
Running gcov: 'llvm-cov gcov /var/jenkins/0/workspace/_feature_align-coverage-metrics2/build/unittest-gcc/BRC36xx-5/Release/src/Util/CMakeFiles/Util.dir/Version.cpp.gcno --branch-counts --branch-probabilities --preserve-paths --object-directory /var/jenkins/0/workspace/_feature_align-coverage-metrics2/build/unittest-gcc/BRC36xx-5/Release/src/Util/CMakeFiles/Util.dir' in '/tmp/tmp4j6_phqh'
```
The first one is in directory `unittest-clang` and has 64 lines (the correct number), the other two files are in `unittest-gcc` and have lines from 65 to 75 with a comment `/*EOF*/`.
All three files are processed with `llvm-cov gcov` but this command is part of clang and can't be used for gcc.

Can you check if the report is correct if the unittest is only called with clang?

**Comment by dsakilesh** [comment] 2021-04-07 08:33
Hi @Spacetown 

After removing the gcc unittest step and keeping only clang helped and we do not have the issue.

We are generating the sonarqube report with below command. We are providing only the `unittest-clang` path in the below command. Not sure how the `unittest-gcc` gcov files are picked up.

`#!/bin/bash set -eo pipefail source /var/jenkins/0/workspace/_feature_align-coverage-metrics2/toolchain/testing/activate.sh && mkdir gcovreport && python -m gcovr --gcov-executable="llvm-cov gcov" -v --root /var/jenkins/0/workspace/_feature_align-coverage-metrics2 --branches -f '/var/jenkins/0/workspace/_feature_align-coverage-metrics2/build/unittest-clang/BRC36xx-5/Debug/(src|include)/' -f '/var/jenkins/0/workspace/_feature_align-coverage-metrics2/src/(src|include)/' --object-dir=. --html-details=gcovreport/index.html --sonarqube=gcovreport/sonarqube.xml`

We run `unittest-clang` and `unittest-gcc` parallely atm. So should we run the unittest-gcc after the `sonarqube.xml` report generation to avoid this error?

Is there an alternate mechanism to make it work even though we run them parallelly?

Thanks in advance!

**Comment by dsakilesh** [comment] 2021-04-07 09:17
Hi @Spacetown 

We have the same issue in a different project even though we run the unittest for clang alone.

We still have `/*EOF*/` lines.

Filename with error :` ConfigurationInstaller.cpp`

PFB the command(same as other project):
`mkdir gcovreport && python -m gcovr --gcov-executable="llvm-cov gcov" -v --root /var/jenkins/0/workspace/_feature_align-coverage-metrics2 --branches -f '/var/jenkins/0/workspace/_feature_align-coverage-metrics2/build/unittest-clang/BRC36xx-5/Debug/(src|include)/' -f '/var/jenkins/0/workspace/_feature_align-coverage-metrics2/src/(src|include)/' --object-dir=. --html-details=gcovreport/index.html --sonarqube=gcovreport/sonarqube.xml `

PFA the console output of the gcovr report generation.
[output.txt](https://github.com/gcovr/gcovr/files/6270417/output.txt)

**Comment by latk** [comment] 2021-04-07 13:56
Perhaps this is one of the rare cases where the `--exclude-dirs` option is useful, in order to tell gcovr to ignore .gcno/.gcda files in certain directories.

**Comment by Spacetown** [comment] 2021-04-07 20:29
> We are generating the sonarqube report with below command. We are providing only the `unittest-clang` path in the below command. Not sure how the `unittest-gcc` gcov files are picked up.
> 
> `#!/bin/bash set -eo pipefail source /var/jenkins/0/workspace/_feature_align-coverage-metrics2/toolchain/testing/activate.sh && mkdir gcovreport && python -m gcovr --gcov-executable="llvm-cov gcov" -v --root /var/jenkins/0/workspace/_feature_align-coverage-metrics2 --branches -f '/var/jenkins/0/workspace/_feature_align-coverage-metrics2/build/unittest-clang/BRC36xx-5/Debug/(src|include)/' -f '/var/jenkins/0/workspace/_feature_align-coverage-metrics2/src/(src|include)/' --object-dir=. --html-details=gcovreport/index.html --sonarqube=gcovreport/sonarqube.xml`

You're using `--root /var/jenkins/0/workspace/_feature_align-coverage-metrics2` and `build/unittest-gcc` is a sub directory of this root.

The other problem is interresting, the output directory is `unittest-clang` and the tool `llvm gcov` which seams to be correct. Are the files in the director realy created with clang?
For me it seems that `llvm gcov` can't read the files generated by `clang` correct. doe the versions of the tool match?

**Comment by dsakilesh** [comment] 2021-04-08 07:09
Hi @Spacetown @latk 

`--exclude-directories` option seems to also work even after adding the `unittest-gcc` i.e, unittest is called with clang and gcc.
 
> The other problem is interresting, the output directory is `unittest-clang` and the tool `llvm gcov` which seams to be correct. Are the files in the director realy created with clang?
> For me it seems that `llvm gcov` can't read the files generated by `clang` correct. doe the versions of the tool match?

We use the sharedlib approach and all the projects use the same sharedlib and same tool versions.

**Comment by Spacetown** [comment] 2021-04-08 17:41
> ... We use the sharedlib approach ...

What do you mean here? Is a shared library generated with gcc and linked to a executable with clang?

**Comment by dsakilesh** [comment] 2021-04-09 08:47
Hi @Spacetown 

All the projects we run use the same gcovr command and same set of tools for build. Thanks!

**Comment by Spacetown** [comment] 2021-04-12 19:29
> All the projects we run use the same gcovr command and same set of tools for build. Thanks!

But the first log showed that you use two different toolchains in one build. I can only verify the second problem if I have a whole buildlog with the compiler/linker (with whole paths), execution and gcovr run. I guess that there is something mixed like in the first log or the used tool versions are incompatible.

**Comment by dsakilesh** [comment] 2021-04-13 04:03
PFA the complete build log

[brc-application-gcov-issue.zip](https://github.com/gcovr/gcovr/files/6301165/brc-application-gcov-issue.zip)

Thanks in advance!

**Comment by Spacetown** [comment] 2021-04-13 20:48
For me that's the same problem. The compiler is used from conan:
```
/var/jenkins_agent_home/.conan/data/llvm/11.0.0_eb1/eb-artifactory/stable/package/4db1be536558d833e52e862fd84d64d75c2b3656/clang/bin/clang++
```
But the folowing message is a hint that the local installed `llvm-cov` is used instead of the one from conan.
```
Filtering coverage data for file /usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/cpp_type_traits.h
```

**Comment by dsakilesh** [comment] 2021-04-15 06:25
Hi @Spacetown 

I have attached the build log of the successful build from other project.

The lines are available even there

`Filtering coverage data for file /usr/lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/iostream

PFA the console log here

[brc3-common-success-build.txt](https://github.com/gcovr/gcovr/files/6315556/brc3-common-success-build.txt)

`

**Comment by Spacetown** [comment] 2021-04-15 06:37
@dsakilesh I don't no the internals of gcov but gcov definitively reports this wrong line numbers for some files and there is a mismatch between the tool versions.
Please try to use the lcov from conan.

**Comment by dsakilesh** [comment] 2021-04-15 07:33
Hi @Spacetown 
I can confirm that we are using the conan package here. We do not have llvm-cov installed in our jenkins executor, it is being installed as part of conan.

PFB the llvm-cov output

without conan env
```
jenkins@0ae43548b877:/usr/lib/x86_64-linux-gnu$ llvm-cov
bash: llvm-cov: command not found
```
with conan env
```
jenkins@0ae43548b877:/usr/lib/x86_64-linux-gnu$ source /var/jenkins/0/workspace/_feature_align-coverage-metrics2/toolchain/hardware/activate.sh
(conanenv) jenkins@0ae43548b877:/usr/lib/x86_64-linux-gnu$ llvm-cov --version
LLVM.org LLVM version 11.0.0
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: cascadelake
```

**Comment by Spacetown** [comment] 2021-04-15 15:36
@dsakilesh Can you provide the output of the following commands with and without Conan environment?
```
which clang++
clang++ - - version
which llvm-gcov
llvm-gcov - - version
```

**Comment by dsakilesh** [comment] 2021-04-16 04:37
@Spacetown 

without conan env:

```
jenkins@0ae43548b877:/var/jenkins/0/workspace/_feature_align-coverage-metrics2$ which clang++
jenkins@0ae43548b877:/var/jenkins/0/workspace/_feature_align-coverage-metrics2$ clang++ --version
bash: clang++: command not found
jenkins@0ae43548b877:/var/jenkins/0/workspace/_feature_align-coverage-metrics2$ which llvm-gcov
jenkins@0ae43548b877:/var/jenkins/0/workspace/_feature_align-coverage-metrics2$ llvm-gcov --version
bash: llvm-gcov: command not found
jenkins@0ae43548b877:/var/jenkins/0/workspace/_feature_align-coverage-metrics2$ which llvm-cov
jenkins@0ae43548b877:/var/jenkins/0/workspace/_feature_align-coverage-metrics2$ llvm-cov --version
bash: llvm-cov: command not found
```

without conan env:

```
jenkins@0ae43548b877:/var/jenkins/0/workspace/_feature_align-coverage-metrics2$ source /var/jenkins/0/workspace/_feature_align-coverage-metrics2/toolchain/hardware/activate.sh
(conanenv) jenkins@0ae43548b877:/var/jenkins/0/workspace/_feature_align-coverage-metrics2$ which clang++
/var/jenkins_agent_home/.conan/data/llvm/11.0.0_eb1/eb-artifactory/stable/package/4db1be536558d833e52e862fd84d64d75c2b3656/clang/bin/clang++
(conanenv) jenkins@0ae43548b877:/var/jenkins/0/workspace/_feature_align-coverage-metrics2$ clang++ --version
LLVM.org clang version 11.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /var/jenkins_agent_home/.conan/data/llvm/11.0.0_eb1/eb-artifactory/stable/package/4db1be536558d833e52e862fd84d64d75c2b3656/clang/bin
(conanenv) jenkins@0ae43548b877:/var/jenkins/0/workspace/_feature_align-coverage-metrics2$ which llvm-gcov
(conanenv) jenkins@0ae43548b877:/var/jenkins/0/workspace/_feature_align-coverage-metrics2$ llvm-gcov --version
bash: llvm-gcov: command not found
(conanenv) jenkins@0ae43548b877:/var/jenkins/0/workspace/_feature_align-coverage-metrics2$ which llvm-cov
/var/jenkins_agent_home/.conan/data/llvm/11.0.0_eb1/eb-artifactory/stable/package/4db1be536558d833e52e862fd84d64d75c2b3656/clang/bin/llvm-cov
(conanenv) jenkins@0ae43548b877:/var/jenkins/0/workspace/_feature_align-coverage-metrics2$ llvm-cov --version
LLVM.org LLVM version 11.0.0
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: cascadelake
```

**Comment by Spacetown** [comment] 2021-04-16 20:39
@dsakilesh I've checked the logs again and found no error. For me it seems to be a error in `llvm-cov gcov` which reads the coverage data and prints the `/*EOF*/` to the report which is read by `gcovr`.
@latk I think we should also adapt the HTML to abort or warn if we have more coverage lines than source lines.

**Comment by Spacetown** [comment] 2021-04-20 19:29
@dsakilesh Please can you check if the warning occures on this branch? You don't need the other changes in the logging and the `--verbose`.

**Comment by dsakilesh** [comment] 2021-04-21 06:36
Hi @Spacetown 

Our gcovr package does not contain the **gcovr/write.html.py** instead contains **gcovr/html_generator.py** and all other dependencies have changed when compared to 4.2 tag (from which our package has been created)  

Could you please create the branch from the **4.2 tag** version of gcovr ?

Thanks in advance!

**Comment by Spacetown** [comment] 2021-04-23 17:37
@dsakilesh Here you are.

**Comment by dsakilesh** [comment] 2021-04-26 07:49
Hi @Spacetown 
We get the below error when we make the changes:

```
Traceback (most recent call last):
  File "/var/jenkins_agent_home/.conan/data/python/3.7.4_eb12/eb-artifactory/stable/package/5ab4f8aef8197f0274f4af1ba8675e9adf31c782/python-3.7.4/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/var/jenkins_agent_home/.conan/data/python/3.7.4_eb12/eb-artifactory/stable/package/5ab4f8aef8197f0274f4af1ba8675e9adf31c782/python-3.7.4/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/jenkins_agent_home/.conan/data/gcovr/4.2_eb7/eb-artifactory/python_3.7.4/package/d06b6bbfc9c35ecf5da8dd2ac3fd83ef0254b72d/gcovr-4.2/gcovr/__main__.py", line 382, in <module>
    main()
  File "/var/jenkins_agent_home/.conan/data/gcovr/4.2_eb7/eb-artifactory/python_3.7.4/package/d06b6bbfc9c35ecf5da8dd2ac3fd83ef0254b72d/gcovr-4.2/gcovr/__main__.py", line 253, in main
    print_reports(covdata, options, logger)
  File "/var/jenkins_agent_home/.conan/data/gcovr/4.2_eb7/eb-artifactory/python_3.7.4/package/d06b6bbfc9c35ecf5da8dd2ac3fd83ef0254b72d/gcovr-4.2/gcovr/__main__.py", line 368, in print_reports
    generator(covdata, output.value, options)
  File "/var/jenkins_agent_home/.conan/data/gcovr/4.2_eb7/eb-artifactory/python_3.7.4/package/d06b6bbfc9c35ecf5da8dd2ac3fd83ef0254b72d/gcovr-4.2/gcovr/html_generator.py", line 258, in print_html_report
    filename=data['filename'],
KeyError: 'filename'
```
We tried replacing the filename with **ConfigurationInstaller.cpp** and also face similar error:

```
Traceback (most recent call last):
  File "/var/jenkins_agent_home/.conan/data/python/3.7.4_eb12/eb-artifactory/stable/package/5ab4f8aef8197f0274f4af1ba8675e9adf31c782/python-3.7.4/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/var/jenkins_agent_home/.conan/data/python/3.7.4_eb12/eb-artifactory/stable/package/5ab4f8aef8197f0274f4af1ba8675e9adf31c782/python-3.7.4/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/jenkins_agent_home/.conan/data/gcovr/4.2_eb7/eb-artifactory/python_3.7.4/package/d06b6bbfc9c35ecf5da8dd2ac3fd83ef0254b72d/gcovr-4.2/gcovr/__main__.py", line 382, in <module>
    main()
  File "/var/jenkins_agent_home/.conan/data/gcovr/4.2_eb7/eb-artifactory/python_3.7.4/package/d06b6bbfc9c35ecf5da8dd2ac3fd83ef0254b72d/gcovr-4.2/gcovr/__main__.py", line 253, in main
    print_reports(covdata, options, logger)
  File "/var/jenkins_agent_home/.conan/data/gcovr/4.2_eb7/eb-artifactory/python_3.7.4/package/d06b6bbfc9c35ecf5da8dd2ac3fd83ef0254b72d/gcovr-4.2/gcovr/__main__.py", line 368, in print_reports
    generator(covdata, output.value, options)
  File "/var/jenkins_agent_home/.conan/data/gcovr/4.2_eb7/eb-artifactory/python_3.7.4/package/d06b6bbfc9c35ecf5da8dd2ac3fd83ef0254b72d/gcovr-4.2/gcovr/html_generator.py", line 258, in print_html_report
    filename=data['ConfigurationInstaller.cpp'],
KeyError: 'ConfigurationInstaller.cpp'
```

**Comment by dsakilesh** [comment] 2021-05-04 12:48
Hi @Spacetown 

Any update here ? :)

**Comment by Spacetown** [comment] 2021-05-04 12:53
https://github.com/Spacetown/gcovr/tree/warn_wrong_line_number_4.2 was updated 8 days ago but it seems that I forgot to comment it.

**Comment by dsakilesh** [comment] 2021-05-05 09:03
Thanks @Spacetown 
We have modified the code in **html_generator.py** as we had issues with print statement.

```
            if ctr < max_line_from_cdata:
                filename=data['FILENAME'],
                file_lines=ctr,
                cdata_lines=max_line_from_cdata
                print(
                    'WARNING: File ' + str(filename) + ' has ' + str(file_lines) + ' line(s) but coverage data has ' + str(cdata_lines) + ' line(s).'
                )
```

PFB the list of **Warnings** after the execution :

```
WARNING: File src/src/ButtonManager/HardwareButtonHandler.cpp has 73 line(s) but coverage data has 74 line(s).
WARNING: File src/src/ConfigurationInstaller/ConfigurationInstaller.cpp has 145 line(s) but coverage data has 155 line(s).
WARNING: File src/src/Filesystem/Filesystem.cpp has 258 line(s) but coverage data has 549 line(s).
WARNING: File src/src/Lbtp/Client.cpp has 224 line(s) but coverage data has 404 line(s).
WARNING: File src/src/Led/Patterns/AssistanceModePattern.cpp has 46 line(s) but coverage data has 82 line(s).
WARNING: File src/src/SystemUpdater/AllComponents.cpp has 44 line(s) but coverage data has 177 line(s).
WARNING: File src/src/SystemUpdater/ComponentBase.cpp has 221 line(s) but coverage data has 417 line(s).
WARNING: File src/src/Ui/Data/BatteryPackData.cpp has 53 line(s) but coverage data has 85 line(s).
WARNING: File src/src/Ui/Views/BackgroundView.cpp has 69 line(s) but coverage data has 76 line(s).
WARNING: File src/src/Ui/Views/BlePairingModeView.cpp has 128 line(s) but coverage data has 194 line(s).
WARNING: File src/src/Ui/Views/CriticalErrorView.cpp has 56 line(s) but coverage data has 78 line(s).
WARNING: File src/src/Ui/Views/DiagnosisProgramView.cpp has 35 line(s) but coverage data has 69 line(s).
WARNING: File src/src/Ui/Views/GoodByeView.cpp has 60 line(s) but coverage data has 79 line(s).
WARNING: File src/src/Ui/Views/NonCriticalErrorView.cpp has 83 line(s) but coverage data has 97 line(s).
WARNING: File src/src/Ui/Views/SoftwareUpdateView.cpp has 80 line(s) but coverage data has 88 line(s).
WARNING: File src/src/Ui/Views/StateOfChargeView.cpp has 60 line(s) but coverage data has 92 line(s).
WARNING: File src/src/Ui/Views/WalkAssistActiveStateView.cpp has 62 line(s) but coverage data has 69 line(s).
WARNING: File src/src/Ui/Views/WelcomeView.cpp has 52 line(s) but coverage data has 76 line(s).
```

**Comment by Spacetown** [comment] 2021-05-05 18:11
It"s strange but for me this is a problem of clang.  In #484  I've added clang-10 I'll try to add a error if the number of lines differ to see if this version is working.
Can you check clang-10 in your project?

**Comment by dsakilesh** [comment] 2021-05-07 05:04
Hi @Spacetown 

We have the same issue even with clang 10 version

```
(conanenv) jenkins@85b5304b4b24:/var/jenkins/0/workspace/s-brc3-application_gcovr-clang10$ clang++ --version
clang version 10.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /var/jenkins_agent_home/.conan/data/llvm/10.0.0_eb1/eb-artifactory/stable/package/4db1be536558d833e52e862fd84d64d75c2b3656/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04/bin
```

**Comment by dsakilesh** [comment] 2021-06-25 07:13
Hi @Spacetown 

Request you to delete the file in the comment 
https://github.com/gcovr/gcovr/issues/345#issuecomment-814394660

Thanks in advance!

**Comment by Spacetown** [comment] 2021-06-25 08:01
@latk In the old version of the comment the file is present. Do you know how to delete it permanent?

**Comment by latk** [comment] 2021-06-25 08:38
Hello @dsakilesh, could you contact me privately at `opensource at lukasatkinson dot de` to discuss this?

@Spacetown fyi deletion of comment history is documented at [GitHub docs](https://docs.github.com/en/communities/moderating-comments-and-conversations/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history) but this will not delete the attachment itself, only the link to it.

**Comment by Spacetown** [comment] 2021-07-19 19:10
Closed because lines are reported wrong by `llvm-gcov`.

**Closed by Spacetown** 2021-07-19 19:10 UTC
Labels: LLVM, Platform: macOS, Type: Bug
