### ISSUE TITLE
always return "make (e=5): Access is denied." when use gcovr

### ISSUE THREAD

**Issue by Darwin-Li-001** [gcovr/gcovr#629] opened 2022-06-01 05:45 UTC
I have tried gcovr 3.2/4.8/5.1.
And i use this too with CMake.
but when i execute 'make coverage' command.  It always give below error back:
C:\Downloads\gcovr-3.2\gcovr -r C:/Keil_v5/Projects/TripodAppwithUT/TripodControlApp/Test/src --object-dir= C:/Test/build -e test_*
process_begin: CreateProcess(NULL, C:\Downloads\gcovr-3.2\gcovr -r C:/Test/src --object-dir= C:/Test/build -e test_*, ...) failed.

make (e=5): Access is denied.

Please help!!! As this problem really bother me for a long time!!!

**Comment by Spacetown** [comment] 2022-06-01 06:02
Gcovr isn't an executable, it's a Python module called like this:
```
python3 -m gcovr ...
```

**Comment by Darwin-Li-001** [comment] 2022-06-02 03:18
> Gcovr isn't an executable, it's a Python module called like this:
> 
> ```
> python3 -m gcovr ...
> ```

Hi Spacetown, Thank you very much for your quick reply!
I use gcovr with CMake, which is also a open source project.  so the commands execute automatically.
please refer to https://github.com/bilke/cmake-modules/blob/master/CodeCoverage.cmake

**Comment by Spacetown** [comment] 2022-06-02 19:24
Ok, in the version 3.2 it was a script not a module.
@latk Can you help here? This was before I joint the project.

**Comment by latk** [comment] 2022-06-03 09:04
There are three issues at hand:

* using gcovr 3.2
* getting Error 5 Access Denied
* using the CodeCoverage CMake module

## Using gcovr 3.2

Gcovr 3.2 was a standalone script. It could be directly downloaded and executed on Linux/Mac. This was never possible on Windows. To run gcovr 3.2 on Windows, one of the following had to be done:

* Python was invoked with that script as an argument, for example `python2.7.exe C:\Downloads\gcovr`
* The gcovr package was installed via the `pip` tool, which would make it possible to directly invoke `gcovr` on the command line.

I cannot recommend using gcovr 3.2 right now. It has countless bugs, it is partially broken under Python 3, and it doesn't support Windows very well. I would strongly suggest to update to at least gcovr 4.2.

## Error 5 Access Denied

I have never used gcovr under Windows so I'm not sure what the cause is. Under Linux, I would expect similar problems if a downloaded script was not marked as executable. I have read reports that similar errors were also caused by anti-virus software.

It is important to note that this error is already caused by `CreateProcess()`, so that gcovr doesn't even run.

## The CodeCoverage CMake module

Those CMake modules are a third party project so I can't help with them. Skimming the CMake file, it seems that they expect at least gcovr 4.2. If you haven't properly installed gcovr (e.g. by installing it via the `pip` tool), then you may have to override a variable to point to the correct location. If you want to change which gcovr installation to use, you may have to re-run `cmake` to update its cache. For help with using the CodeCoverage module, you'll have to contact its authors (but I'll be happy to help them if they have questions about invoking gcovr correctly).

**Closed** 2022-08-05 18:31 UTC
Labels: Type: Question
