### ISSUE TITLE
Sporadic gcovr error in Github Actions `UnknownLineType`

### ISSUE THREAD

**Issue by jparisu** [gcovr/gcovr#614] opened 2022-04-19 08:45 UTC
**Describe the bug**
We are encountering a sporadic failure when running `gcovr` in out CI using Github Actions.
The error could be found here: https://github.com/eProsima/DDS-Router/runs/6072951246?check_suite_focus=true (the only failure point of the workflow) and it says:
```
gcovr.gcov_parser.UnknownLineType: branch  1 taken -1
(ERROR) Uncaught EXCEPTION
```
This error is becoming more and more common, and it is breaking our CI constantly.

**To Reproduce**
It is an error that we only encounter in our CI.
The error could be seen here: https://github.com/eProsima/DDS-Router/runs/6072951246?check_suite_focus=true
Much of the times the error does not appear. Could be seen in the CI of the same repo: https://github.com/eProsima/DDS-Router/actions

**Expected behavior**
The expected behavior is to gcovr to run without failing. Or at least to fail consistently in case there is some error there.

**Desktop (please complete the following information):**
 - OS: ubuntu-latest (Github Action)
 - GCC version : Ubuntu 9.4.0-1ubuntu1~20.04.1
 - GCOVR version : 4.2

**Comment by latk** [comment] 2022-04-19 09:43
You are using gcovr 5.1, which introduced a more accurate parser for the gcov file format. You are experiencing a common bug that surfaced in that version (compare #583, #610, and so on). The cause is not clear:

* Either, gcov is already producing corrupted coverage reports. This can't be fixed by gcovr, but such errors can be explicitly ignored with the `--gcov-ignore-parse-errors` option. Of course, this will lead to less correct coverage reports that are simply missing some data.
* Or, gcovr is doing something wrong when reading the coverage reports. In particular, gcovr 5.1 has some bugs relating to parallel processing of data (fixed in #592). You do not seem to be using the `-j/gcov-parallel` mode, so this shouldn't be the cause – but it's possible there are some related issues. The fix is not yet part of a release, but it's possible to install the gcovr development version directly from this GitHub repository. Maybe it happens to help – if so, that would be a very interesting piece of the puzzle.

Since this is a duplicate issue and mitigations exist, I am closing this issue.

As an aside, I noticed that you are using the `--object-directory` option. This is almost always incorrect since it overrides/disables normal behaviour. If you have coverage data (.gcda and .gcno files) in multiple directories, you can tell gcovr to look there by listing explicit `search_paths`. Moving coverage data into a different location (such as with your `cp --recursive build/ddsrouter_* build/ddsrouter` command) makes it less likely for gcovr to be able to create correct coverage reports. But that is definitely unrelated to the issues you are seeing.

**Closed by latk** 2022-04-19 09:43 UTC
Labels: Type: Bug

**Comment by jparisu** [comment] 2022-04-21 05:49
It works fine with version 5.0 . And we changed our CI so it does not use `--object-directory` anymore.

We would like to use the last release when this issue is fixed. Where can I attach in order to be notified about news in this issue?

Thank you very much for the support.

**Comment by Spacetown** [comment] 2022-04-21 06:56
You can watch the activities in this repository. There is also a point to watch only releases.
