### ISSUE TITLE
Incorrect paths for header files

### ISSUE THREAD

**Issue by ZedThree** [gcovr/gcovr#271] opened 2018-07-12 12:35 UTC
Header files don't seem to be dealt with correctly:

```bash
$ gcovr -j8 -r . --html-details -o gcovr-report/coverage.html -dTraceback (most recent call last):
  File "/home/p/.local/bin/gcovr", line 11, in <module>
    sys.exit(main())
  File "/home/p/.local/lib/python3.6/site-packages/gcovr/__main__.py", line 588, in main
    print_html_report(covdata, options)
  File "/home/p/.local/lib/python3.6/site-packages/gcovr/html_generator.py", line 275, in print_html_report
    errors='replace')
FileNotFoundError: [Errno 2] No such file or directory: 'src/array.hxx'
```

While `--html-details` throws an error, just running `gcovr` counts each header separately for each directory containing a source file that includes it, so I get stuff like:

```
------------------ ...
File               ...
------------------ ...
src/dir1/array.hxx ...
src/dir2/array.hxx ...
...
```

If I keep the gcov files, I can see they have the correct names, i.e.:

```
./^#include#array.hxx.gcov
./src/dir1/^#^#include#array.hxx.gcov
./src/dir2/^#^#include#array.hxx.gcov
```

This is with gcovr version 4.1 and gcc 8.1

**Comment by latk** [comment] 2018-07-12 12:49
Thank you for reporting this problem, you're right that gcovr
behaviour seems to be completely bonkers in this case. I'll try to
take a look during the weekend.

It would help immensely if you could add the following:

1. the first few lines of all involved gcov files (they contain the
actual source file name; the gcov file name is not reliable)

2. a short hello-world style example to reproduce the issue so that I
can experiment on this myself. I.e. the necessary file contents,
directory layouts, and compiler flags.

**Comment by latk** [comment] 2018-07-21 07:50
This issue has not seen any progress in a while, so I am closing it for now. If the problem persists, please add further details so it can be re-opened. If someone else is experiencing a similar issue, please create a new issue.

**Comment by ZedThree** [comment] 2018-07-24 09:01
Sorry for the late reply, I went on holiday before I got round to updating this! Apologies for the following information dump...

Here is a zipfile containing a complete toy problem: 
[gcovr-271.zip](https://github.com/gcovr/gcovr/files/2222769/gcovr-271.zip)

Directory layout is as follows:

```
├── make.config
├── makefile
├── include
│   ├── makefile
│   ├── sys
│   │   └── foo.hxx
│   └── toy.hxx
├── src
│   ├── makefile
│   ├── sys
│   │   ├── foo.cxx
│   │   └── makefile
│   └── toy.cxx
└── test
    ├── makefile
    └── test.cxx
```
Also included is `compile_commands.json`.

Running:
```
make
make check
```
should print:
```
thing is : 4
bar
foo

test
```

Here is the output of `gcovr -r . -k -s`:
```
------------------------------------------------------------------------------
                           GCC Code Coverage Report
Directory: .
------------------------------------------------------------------------------
File                                       Lines    Exec  Cover   Missing
------------------------------------------------------------------------------
src/foo.hxx                                    2       0     0%   9-10
src/sys/foo.cxx                                9       9   100%   
src/toy.cxx                                   10      10   100%   
src/toy.hxx                                    4       4   100%   
test/foo.hxx                                   2       2   100%   
test/test.cxx                                  6       6   100%   
------------------------------------------------------------------------------
TOTAL                                         33      31    93%
------------------------------------------------------------------------------
lines: 93.9% (31 out of 33)
branches: 52.6% (20 out of 38)
```
Notice that `foo.hxx` is included twice, once with 0% coverage. Neither header file (`foo.hxx`, `toy.hxx`) is under `include/`. The makefile has a `code-coverage-capture` target that uses `lcov`, which reports everything correctly, so I don't think it's something fundamentally wrong with our setup. Unfortunately, `lcov` automatically cleans up the gcov files it generates, with no option to keep them, so it's not possible to directly compare them. I have a suspicion it's something to do with our recursive-make build system and needing to run gcov in the correct locations, but I'm not certain.

Finally, here is the output of `find . -type f -name "*.gcov" | xargs head` (after getting rid of the files from system headers):

```

==> ./src/sys/foo.cxx.gcov <==
        -:    0:Source:foo.cxx
        -:    0:Graph:/home/user/gcovr-271/src/sys/foo.gcno
        -:    0:Data:/home/user/gcovr-271/src/sys/foo.gcda
        -:    0:Runs:1
        -:    0:Programs:1
        -:    1:#include "sys/foo.hxx"
        -:    2:
function _ZN3Foo4pushENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE called 3 returned 100% blocks executed 100%
        3:    3:void Foo::push(std::string str) {
        3:    4:  stack.push_back(std::move(str));

==> ./src/toy.cxx.gcov <==
        -:    0:Source:toy.cxx
        -:    0:Graph:/home/user/gcovr-271/src/toy.gcno
        -:    0:Data:/home/user/gcovr-271/src/toy.gcda
        -:    0:Runs:1
        -:    0:Programs:1
        -:    1:#include "toy.hxx"
        -:    2:#include "sys/foo.hxx"
        -:    3:
        -:    4:#include <iostream>
        -:    5:

==> ./src/^#include#sys#foo.hxx.gcov <==
        -:    0:Source:../include/sys/foo.hxx
        -:    0:Graph:/home/user/gcovr-271/src/toy.gcno
        -:    0:Data:/home/user/gcovr-271/src/toy.gcda
        -:    0:Runs:1
        -:    0:Programs:1
        -:    1:#ifndef __FOO_H__
        -:    2:#define __FOO_H__
        -:    3:
        -:    4:#include <string>
        -:    5:#include <vector>

==> ./src/^#include#toy.hxx.gcov <==
        -:    0:Source:../include/toy.hxx
        -:    0:Graph:/home/user/gcovr-271/src/toy.gcno
        -:    0:Data:/home/user/gcovr-271/src/toy.gcda
        -:    0:Runs:1
        -:    0:Programs:1
        -:    1:#ifndef __TOY_H__
        -:    2:#define __TOY_H__
        -:    3:
        -:    4:#include <iostream>
        -:    5:

==> ./test/test.cxx.gcov <==
        -:    0:Source:test.cxx
        -:    0:Graph:/home/user/gcovr-271/test/test.gcno
        -:    0:Data:/home/user/gcovr-271/test/test.gcda
        -:    0:Runs:1
        -:    0:Programs:1
        -:    1:#include "toy.hxx"
        -:    2:#include "sys/foo.hxx"
        -:    3:
function main called 1 returned 100% blocks executed 67%
        1:    4:int main() {

==> ./test/^#include#sys#foo.hxx.gcov <==
        -:    0:Source:../include/sys/foo.hxx
        -:    0:Graph:/home/user/gcovr-271/test/test.gcno
        -:    0:Data:/home/user/gcovr-271/test/test.gcda
        -:    0:Runs:1
        -:    0:Programs:1
        -:    1:#ifndef __FOO_H__
        -:    2:#define __FOO_H__
        -:    3:
        -:    4:#include <string>
        -:    5:#include <vector>

==> ./test.cxx.gcov <==
        -:    0:Source:test.cxx
        -:    0:Graph:/home/user/gcovr-271/test/test.gcno
        -:    0:Data:/home/user/gcovr-271/test/test.gcda
        -:    0:Runs:1
        -:    0:Programs:1

==> ./^#include#sys#foo.hxx.gcov <==
        -:    0:Source:../include/sys/foo.hxx
        -:    0:Graph:/home/user/gcovr-271/src/toy.gcno
        -:    0:Data:/home/user/gcovr-271/src/toy.gcda
        -:    0:Runs:1
        -:    0:Programs:1

==> ./toy.cxx.gcov <==
        -:    0:Source:toy.cxx
        -:    0:Graph:/home/user/gcovr-271/src/toy.gcno
        -:    0:Data:/home/user/gcovr-271/src/toy.gcda
        -:    0:Runs:1
        -:    0:Programs:1

==> ./^#include#toy.hxx.gcov <==
        -:    0:Source:../include/toy.hxx
        -:    0:Graph:/home/user/gcovr-271/src/toy.gcno
        -:    0:Data:/home/user/gcovr-271/src/toy.gcda
        -:    0:Runs:1
        -:    0:Programs:1

==> ./foo.cxx.gcov <==
        -:    0:Source:foo.cxx
        -:    0:Graph:/home/user/gcovr-271/src/sys/foo.gcno
        -:    0:Data:/home/user/gcovr-271/src/sys/foo.gcda
        -:    0:Runs:1
        -:    0:Programs:1
```

**Comment by latk** [comment] 2018-07-24 09:29
No problems, I hope you had relaxing holidays :)

When you look at the three foo.hxx.gcov files you'll see they all point to
their source file in the first line. Unfortunately this relative path is a
lie and is not relative to the gcov file. Gcovr uses various heuristics to
find the real source file, here they fail to work correctly.

I'll look into your test case more deeply as soon as I find the time. Thank
you for providing really comprehensive information about your scenario! If
you want to experiment a bit you can try whether the --object-directory
option fixes anything, as it switches to a different set of heuristics (but
I don't quite understand that part of the code).

Peter Hill <notifications@github.com> schrieb am Di., 24. Juli 2018, 11:01:

**Comment by lisongmin** [comment] 2018-08-04 14:10
It may cause by `-I../include` option, and we should try real source file relative to the source directory.

```
  currdir      /tmp/abc
  gcov_fname   /tmp/tmpu47t14wr/^#include#toy.hxx.gcov
               ['        -', '    0', 'Source', '../include/toy.hxx\n']
  source_fname /tmp/abc/src/toy.gcda
  root         /tmp/abc
  fname        /tmp/abc/src/toy.hxx
```

now fname is `dirname(source_fname) + basename(gcov_fname)` 
* fname        /tmp/abc/src/toy.hxx

which should be `realpath(dirname(source_fname) + gcov_fname)`
* fname        /tmp/abc/include/toy.hxx

without realpath `test/../include/toy.hxx` and `src/../include/toy.hxx` may consider as two different files.

```diff
@@ -196,8 +198,13 @@ def guess_source_file_name_heuristics(
     if os.path.exists(fname):
         return fname

-    # 3. Try using the path to the gcda file as the source directory
+    # 3. Try using the path relative to source directory
     source_fname_dir = os.path.dirname(source_fname)
+    fname = os.path.join(source_fname_dir, gcovname)
+    if os.path.exists(fname):
+        return os.path.realpath(fname)
+
+    # 4. Try using the path to the gcda file as the source directory
     fname = os.path.join(source_fname_dir, os.path.basename(gcovname))
     return fname
```


```
------------------------------------------------------------------------------
                           GCC Code Coverage Report
Directory: .
------------------------------------------------------------------------------
File                                       Lines    Exec  Cover   Missing
------------------------------------------------------------------------------
include/sys/foo.hxx                            2       2   100%
include/toy.hxx                                4       4   100%
src/sys/foo.cxx                                9       9   100%
src/toy.cxx                                   10      10   100%
test/test.cxx                                  6       6   100%
------------------------------------------------------------------------------
TOTAL                                         31      31   100%
------------------------------------------------------------------------------
```

**Comment by latk** [comment] 2018-08-05 17:52
Thank you @lisongmin, you are absolutely right that we should use `realpath()` here – in fact, we should use `realpath()` for _all_ the heuristics in that function.

I am not quite sure whether it is correct to resolve the source code path relative to the gcda file (confusingly called `source_fname` in the code). I think the source code paths should be interpreted relative to the original GCC working directory. In this particular example they are the same because of an in-source build, but not in general. Gcovr's guess for the GCC working directory is called `chdir` in `run_gcov_and_process_files()`.

During the last few weeks I've been spending some time on gcovr's path heuristics. There's a lot of weird code around there and I hope to clean some of it up soon. Gcovr tends to make some assumptions about the build process that are not always a good fit in the real world, e.g. either GCC is invoked somewhere in the build directory or from the --root. This recursive-Makefile approach combined with a separate build directory would probably break the heuristics (haven't tested it yet).

I am super thankful for this issue because it exposes some of these bad assumptions!

**Comment by lisongmin** [comment] 2018-08-06 13:48
Be aware symlink may changed via realpath(). This may affect to filter in some case.

**Comment by darkmattercoder** [comment] 2018-12-03 09:42
Hi,

is there anything that I can help with? I also experience those things. Shall I post outputs similar to the above?

**Comment by latk** [comment] 2018-12-06 23:06
I now have a bit of time to look at issues again since I completed an important project today.

The core problem is that I don't understand what gcov's relative `Source` paths mean precisely: what directory are they relative to? The gcda file? The source file? The compiler invocation directory? The gcov invocation directory? Could this be solved if gcovr is also given any `-I` options?

I'll try looking at the gcov source code and at how lcov handles this, sometime over the next few weeks. If someone is quicker than me and can post an explanation here (with sources/references), that would also be most welcome. I'll also try turning @ZedThree's excellent example into an xfail test case.

Since the HTML details report has to open the source files in order to display the details, it is the only report that will die due to this issue.
Unfortunately the tests currently only run with GCC 5, not more recent versions (#206) and not LLVM (#134). So it's possible that small incompatibilities have been missed.

**Comment by danquist** [comment] 2018-12-07 02:54
Thank you for looking into this @latk!

Judging from the fact I can hardly find any online resources using gcovr with llvm, I must assume it's not a well used feature. I'm not surprised something got broken by mistake.

**Comment by thefifo** [comment] 2019-05-10 10:57
+1 Seeing the issue still with GCC 8.2

**Comment by z3bu** [comment] 2019-05-13 15:22
Same issue with gcc 7.4.0 (gcov alone works
> $ gcc --version
> gcc.exe (Rev1, Built by MSYS2 project) 7.4.0

**Comment by kevinlrak** [comment] 2020-12-02 14:49
I'm seeing this issue currently with gcc 10.2.0.

Recommend changing issue title to "Incorrect paths for Include Path files" since this does not apply to all headers, nor is it restricted to only headers (I'm writing some odd unit tests which are including a `.cpp` file).

**Comment by Mno-hime** [comment] 2022-04-01 09:53
Did https://github.com/gcovr/gcovr/pull/358 resolve this issue?

**Comment by Spacetown** [comment] 2022-04-02 17:33
Can you check this with the branch of #597?

**Comment by Spacetown** [comment] 2022-08-06 22:02
Closing because of missing response. If the problem persists, please reopen.

**Closed** 2022-08-06 22:12 UTC
Labels: Gcov
