### ISSUE TITLE
Is gcovr still maintained?

### ISSUE THREAD

**Issue by pbregener** [gcovr/gcovr#176] opened 2017-08-17 12:08 UTC
Hi @whart222!

There are quite a few open issues and open PRs for the `gcovr` project, and people are opening new tickets and are trying to contribute code (and fix bugs) on a regular basis.  
However, the last commit dates back almost exactly one year ago.
Should we consider `gcovr` unmaintained now? Are you looking for one or several new maintainers? Should someone fork it?

Seems like there are many people who use and like `gcovr` but the lack of progress is somewhat disappointing right now.

**Comment by latk** [comment] 2017-08-17 21:29
I share this concern, and would also like to see more active maintenance. If necessary I'd be willing to help out with that.

By coincidence, I emailed W. Hart about this just yesterday and am waiting for a response. I completely understand if he doesn't want to spend time on this project – any open source work is entirely voluntary, and I'm thankful for his existing contributions. But it would be nice if he could add a couple of interested people to the gcovr organization.

Until there's a response, forking would be premature. That is very much a strategy of last resort. I'd rather see this repo revived. I'm glad to see I'm not the only one looking forward to this :)

**Comment by aoreskovic** [comment] 2017-08-21 18:40
I also emailed W. Hart, 10 days ago, still no response. At this point, I was thinking of cloning this repository and merging the pull request and maintaining it from there forward. I mean if at any point I actually get response or complaint about copyright I would remove the cloned repository. That seems like the best option to keep this project afloat.

**Comment by latk** [comment] 2017-08-21 19:54
@aoreskovic Great to hear that you're also interested in keeping the project going. Since we are now at least three or four people that are interested in this, I'm confident that Gcovr has some kind of bright future :)

I would still wait a bit (~ 2 weeks) before doing a fork. Judging from public activity, Mr. Hart is alive and with internet access, so I expect he'll answer one of us soon.
(@whart222: At this point even a quick comment would be very helpful…)

The problem with forking isn't the copyright – Gcovr is available under the “BSD 3-clause” license which explicitly allows us to make copies, change the code, and distribute changed versions. You can fork now and start hacking.

The problem is rather forking the project: If we fork a new Gcovr we are *competing* with the current Gcovr. Issues I can see:

 - All users are using the current Gcovr. There would be no clear upgrade path.
 - To avoid confusion we should use a new name.
 - When users search for Gcovr, they will find this repository and the Gcovr website, not the forked version.
 - All forked repositories on GitHub will still reference this repo.
 - Gcovr is distributed via PyPI and is included in some Linux distributions. However, only Mr. Hart can upload new versions to PyPI.

Most of those issues can be worked around with some effort and some time – I guess a few years until a fork would be accepted as a successor project.

But none of that is necessary if Mr. Hart adds collaborators to *this* repository. This is easy since the repo already belongs to an organization rather than an individual user. And the Travis CI file is already set up to do PyPI releases for successful builds (though under his account – he may not be comfortable with that). But he seems to be the only one with access to the gcovr organization.

So because a response by Mr. Hart could make all of this so much easier, I'm happy to wait a bit longer.

**Comment by denniswjackson** [comment] 2017-08-23 13:53
I am actively using gcovr at my company as well (and know others who do, too). Forking gives me the most concern for all of the reasons here.

**Comment by aoreskovic** [comment] 2017-08-27 21:48
@latk Agreed, no need to rush!

@denniswjackson To be clear, the continuation of this project is by far the best option, definitely better than forking. If @whart222 adds new developers that would solve all of our problems.

But on the off chance that that doesn't happen I think that fork is better than leaving this project abandoned and forgotten.

**Comment by whart222** [comment] 2017-08-27 23:39
Hi, all:

My apologies, but I haven't been able to follow this conversation until
just now.  I am willing and interested in opening up development of gcovr
to a broader team.  Due to work constraints, this project has been a low
priority for a while.

I'm wrapping up some deadlines in the next few days.  I'll reconnect later
this week to add folks to the repository.

--Bill

**Comment by Flockstud** [comment] 2017-08-29 14:28
Great news! I'm quite interested in using it as it generates xml format coverage which will work great with Jenkins.

**Comment by pbregener** [comment] 2017-08-30 06:52
Thanks @whart222!

I hope to be able to contribute with occasional PRs in the future, but unfortunately I won't be able to continuously spend time on it.

**Comment by sinelaw** [comment] 2017-09-03 07:57
I'm also willing to participant in maintenance work

**Comment by latk** [comment] 2017-09-19 13:55
@whart222 Is there any update on gcovr maintainership status? I just want to merge good pull requests and triage open issues.

 - You can add people to this repository via Settings tab → Collaborators ([link](https://github.com/gcovr/gcovr/settings/collaboration)). This enables push access.
 - You can add people to the @gcovr organization via People tab → Invite Member ([link](https://github.com/orgs/gcovr/people)). Members default to push access to all repos (gcovr + website). If you assign the “Owner” role, they get admin access to the repos.

Thank you!

**Comment by sinelaw** [comment] 2017-10-18 07:50
ping!

**Comment by ligurio** [comment] 2017-11-26 08:12
Ping!

**Comment by c1728p9** [comment] 2017-12-23 02:09
@whart222 have you been able add maintainers to this repo? There are some path issues on windows that make this unusable. It looks like there are multiple PRs to address this, but none of them have been merged.

Alternatively, is anyone maintaining a forked copy who would also like to serve as gatekeeper until @whart222 is able to add collaborators? If PRs can be code reviewed, tested and merged in the fork, then the master branch of the fork can be pushed to this here when access is granted (so there is no duplicated work). @latk would you be interested in taking this role? Let me know and I'll send some PRs to your fork.

**Comment by latk** [comment] 2017-12-23 15:43
@c1728p9 I previously tried to avoid a fork, but now that's clearly the best solution. I'm willing to coordinate PRs at my [latk/gcovr](https://github.com/latk/gcovr) fork. I'm somewhat limited by not having access to a Windows machine, so I'm dependent on your contributions for that.

I am especially interested in PRs about:

- Fixes for Windows path handling.
- QA and build engineering improvements, such as Appveyor configuration. Currently there are no automated tests on Windows.
- Maintainability improvements, such as small refactorings and modularization.
- Updated PRs from this gcovr/gcovr repo.

Otherwise, I would initially like to stay close to whart222's goals for this project, which means: no runtime dependencies outside the standard library, and no installation procedure. A cloned repo should be directly runnable, without having to run a `setup.py`. After the fork turns out to be viable, I'm very willing to create a new gcovr organization (with _multiple_ admins!) and revisit those goals so that gcovr can be modernized gradually.

**Comment by sinelaw** [comment] 2017-12-23 16:14
I think we have no option besides forget at this point. I'm willing to
assist in admin roles

**Comment by jsiirola** [comment] 2017-12-23 17:44
I would hope that we don't need to fork the project.

I cornered @whart222 in the hall a couple weeks ago and we had a quick chat about how to get folks added to the group.  I didn't realize until just now that I had any admin rights for the group.  I have added @latk and @sinelaw to the gcovr developer's group.  That should get things rolling.

We should have a discussion as a group (in this issue?) as how to best manage planning, development, and testing going forward (since we can't rely on wandering by @whart222's office any more ;) ).

I propose the following:
  - set up Travis-CI for testing
  - manage bug fixes through PRs (even for developers)
  - additional folks who want to develop may request developer access and with a second by a current developer will be added.
  - I am happy to entertain an additional admin for the group, but in the open-source meritocracy mindset, what do folks think about self nominations with a concurrence of the supermajority of current developers?

Thoughts?

**Comment by sinelaw** [comment] 2017-12-23 19:38
Sounds good, better than a fork, obviously.

**Comment by sinelaw** [comment] 2017-12-25 07:58
I think it's best if someone takes lead on this, not sure I have time (but I will have time to review pull requests, etc.)
Who's leading this now?

**Comment by sinelaw** [comment] 2017-12-25 08:05
From my end the following features are what I'd like to add:

1. Some easy way to specify ignore custom source code lines (e.g. via regex, like don't count " *PANIC()$" lines as uncovered since they aren't supposed to be called)
2. Output to CSV
3. Expose gcovr as a module with API (get the results in a pythonic data structure) for easier analysis with other python tools (not sure if this is already available or not)

**Comment by latk** [comment] 2017-12-27 12:26
@jsiirola Thank you so much for stepping in.

Now that I have access, I would like to triage the issues and pull requests, using the following critera:

 - Everything related to the "dev"-branch rewrite will be tagged and closed since there has not been any progress in that direction.
 - Bug reports that are not actionable (do not provide steps to reproduce) will be closed.
 - Actionable bug reports will be tagged with "help wanted".
 - A PR will be merged once two members have OK'd it, i.e. I won't merge unless someone else has looked over it. I will tag PRs that are missing reviews.

Any objections or suggestions?

**Regarding development process:**
I agree with @jsiirola's suggestions. Let's perform any discussions here in GH issues, not on the defunct mailing list. Any changes should go through a PR so that they can be reviewed. We should consider making the "master" branch protected in order to enforce this. Travis is already activated. My long-term goal is adding Appveyor builds so that we also have automatic tests on Windows.

**Regarding decisions and votes:**
We don't need any heavyweight process. But we need a way to reach decisions reasonably quickly, without a BDFL role. Votes are good, but must be time-boxed. One week seems reasonable for ordinary decisions, decided by a simple majority. One month/four weeks should leave enough time for major decisions and admin elections, which should be decided by a 2/3 majority. If any policies need to be clarified, that should go through a vote.

**Regarding the "dev" branch:**
It was [started](https://github.com/gcovr/gcovr/pull/55#issuecomment-50207307) as a rewrite/refactoring of gcovr and has diverged significantly from master. But all stable releases and most bug reports are from the master branch. So I think the dev branch should be archived. Ideally some changes can be backported without losing any bugfixes. New work should focus on the master branch.

**Regarding future features:**
The ideas @sinelaw suggested are all very good, but I think they should be discussed as separate issues. Personally, I'm less interested in developing new features and more interested in first working through the backlog of issues, then in quality improvements that simplify outside contributions.

**Regarding PyPI:**
currently Travis seems to be set up to release new versions to PyPI automatically when a tag is created. This uses W. Hart's credentials. That is very convenient. But if he ever feels uncomfortable that we could publish under his name, we can find a way to transfer the PyPI package to another user.

**Regarding admins:**
I would like to take on that role. If the general ideas in this comment are met with agreement, I'll submit a more formal application as a separate issue.

**Comment by sinelaw** [comment] 2017-12-27 12:57
I agree to everything above.

**Comment by denniswjackson** [comment] 2017-12-29 18:53
I agree with all of this.  Where the plans for `dev` documented somewhere?
I use gcovr for projects at work and at a minimum I'm interested in keeping
it running on Windows machines.

**Comment by latk** [comment] 2017-12-29 22:09
> Where the plans for `dev` documented somewhere?

The dev branch was started as a great refactoring in #43 and #55:

On 8 Jul 2014, whart222 wrote in <https://github.com/gcovr/gcovr/pull/43#issuecomment-47948654>:
> This pull request represents a major change to gcovr. Specifically, it decomposes the gcovr script into separate packages.
>
> There are good reasons for doing this, particularly to promote better software engineering of gcovr. However, this fundamentally changes how gcovr is installed and used, since the code is no longer a single script.

On 25 Jul 2014, whart222 wrote in <https://github.com/gcovr/gcovr/pull/55#issuecomment-50207307>:
> I have created a gcovr/dev branch, and I have merged this pull request into that branch. I propose that we develop the new gcovr decomposition in this branch, and once it's stable we move it to gcovr/master. […]

… but two years later:

On 6 Aug 2016, whart222 wrote in <https://github.com/gcovr/gcovr/pull/115#issuecomment-238026567>:
> […] For the master branch, gcovr is a stand-alone script. Hence, dependencies on third-party packages do not make sense.
>
> We have a draft 'dev' branch which decomposes this script, which will foster better code and project maintainability. I'm pretty sure I'm going to move there after then next release. At that point, I'll consider moving to proc.

So in retrospect, the changes on the dev branch are all very good, but this branch has been under development for so long that I find it difficult to tell whether the dev branch has feature parity with the master branch. In the meanwhile, the master branch has seen independent bugfixes from real-world usage.

To avoid this problem in the future:

 - the master branch should be less conservative: changes such as adding new dependencies ought to be possible without having to do a new release.
 - future refactoring should be more incremental, to prevent divergent long-lived branches. Smaller changes also allow better discussions on what designs are preferable, thus preventing to take on more technical debt.

I hope that most of the dev improvements can be backported to master, in particular some or all commits of pr #43. But re-implementing and rebasing these improvements one by one seems far less risky than merging the whole dev branch directly. I am therefore archiving old dev-specific issues so that they can be revisited at a later time.

**Comment by latk** [comment] 2017-12-29 22:17
@denniswjackson: There is no intention whatsoever to stop or degrade Windows support. Actually, I have started fiddling around with AppVeyor in order to provide CI builds on Windows, thus preventing regressions. (Currently there are only CI builds on Linux, using Travis CI.) Unfortunately I don't have a Windows development machine. So far, I haven't been able to run the test suite on AppVeyor.

If you or someone else can contribute experience with running Makefile- and CMake-based builds on MSYS and MinGW-w64, that would be extremely helpful for improving automated testing. Of course, general help with testing gcovr on Windows is welcome as well.

**Comment by wolf99** [comment] 2018-01-02 15:54
Hi @latk, all, my experience with Python and Appveyor is low to non-existent, but I use gcovr for my embedded systems work which I do mostly on a Windows machine (and have thus fiddled around with MSYS2 enough to try running gcovr on Windows). I'd be interested in helping out where if I can, maybe some Windows testing, issue triage, etc.

**Comment by denniswjackson** [comment] 2018-01-02 18:17
My concern over Windows support was before these recent updates with folks
stepping in and maintaining the project.  I'm happy to see all of the new
activity.

I build on cygwin instead of MSYS and MinGW-w64 but I'll help where I can
with updates.  I hadn't heard of AppVeyor before but will read up on it.

-dennis.

**Comment by latk** [comment] 2018-01-06 20:46
Now that the first PRs have been merged after this hiatus, I think I can resolve this issue: yes, gcovr is being maintained :)

Thank you very much to everyone who helped to breathe life back into the project. Please do continue helping by responding to issues and reviewing pull requests, and also by contributing bugfixes. To keep track of what's going on, watch the repository or occasionally take a look at the issues/PRs. I'm tagging good opportunities to contribute with the [help wanted](https://github.com/gcovr/gcovr/labels/help%20wanted) and [needs review](https://github.com/gcovr/gcovr/labels/needs%20review) labels.

**Closed by latk** 2018-01-06 20:46 UTC
